using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class FormsDatum
    {
        public Guid FrmId { get; set; }
        public bool FrmDeleted { get; set; }
        public string Summary { get; set; }
        public byte Type { get; set; }
        public string Source { get; set; }
        public string Notes { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingTown { get; set; }
        public string BillingCounty { get; set; }
        public string BillingPostcode { get; set; }
        public string BillingCountry { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Fax3 { get; set; }
        public string WebSite1 { get; set; }
        public string WebSite2 { get; set; }
        public string BusinessAddressCity { get; set; }
        public string BusinessAddressCountry { get; set; }
        public string BusinessAddressPostalCode { get; set; }
        public string BusinessAddressPostOfficeBox { get; set; }
        public string BusinessAddressState { get; set; }
        public string BusinessAddressStreet { get; set; }
        public string BusinessAddressStreet2 { get; set; }
        public string BusinessAddressStreet3 { get; set; }
        public string BusinessFaxNumber { get; set; }
        public string BusinessHomePage { get; set; }
        public string BusinessTelephoneNumber { get; set; }
        public string Email1Address { get; set; }
        public string Email2Address { get; set; }
        public string Email3Address { get; set; }
        public string FirstName { get; set; }
        public string HomeAddressCity { get; set; }
        public string HomeAddressCountry { get; set; }
        public string HomeAddressPostalCode { get; set; }
        public string HomeAddressPostOfficeBox { get; set; }
        public string HomeAddressState { get; set; }
        public string HomeAddressStreet { get; set; }
        public string HomeAddressStreet2 { get; set; }
        public string HomeAddressStreet3 { get; set; }
        public string HomeFaxNumber { get; set; }
        public string HomeTelephoneNumber { get; set; }
        public string JobTitle { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string MobileTelephoneNumber { get; set; }
        public string Title { get; set; }
        public bool? PreferredContactEmail { get; set; }
        public bool? PreferredContactPhone { get; set; }
        public bool? PreferredContactFax { get; set; }
        public bool? PreferredContactLetter { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string FrmUd1Text { get; set; }
        public string FrmUd2Text { get; set; }
        public string FrmUd3Text { get; set; }
        public string FrmUd4Text { get; set; }
        public string FrmUd5Text { get; set; }
        public string FrmUd6Text { get; set; }
        public string FrmUd7Text { get; set; }
        public string FrmUd8Text { get; set; }
        public string FrmUd9Text { get; set; }
        public string FrmUd10Text { get; set; }
        public string FrmUd11Text { get; set; }
        public string FrmUd12Text { get; set; }
        public string FrmUd13Text { get; set; }
        public string FrmUd14Text { get; set; }
        public string FrmUd15Text { get; set; }
        public string FrmUd16Text { get; set; }
        public string FrmUd17Text { get; set; }
        public string FrmUd18Text { get; set; }
        public string FrmUd19Text { get; set; }
        public string FrmUd20Text { get; set; }
        public string FrmUd21Text { get; set; }
        public string FrmUd22Text { get; set; }
        public string FrmUd23Text { get; set; }
        public string FrmUd24Text { get; set; }
        public string FrmUd25Text { get; set; }
        public string FrmUd26Text { get; set; }
        public string FrmUd27Text { get; set; }
        public string FrmUd28Text { get; set; }
        public string FrmUd29Text { get; set; }
        public string FrmUd30Text { get; set; }
        public DateTime? FrmUd1Date { get; set; }
        public DateTime? FrmUd2Date { get; set; }
        public DateTime? FrmUd3Date { get; set; }
        public DateTime? FrmUd4Date { get; set; }
        public DateTime? FrmUd5Date { get; set; }
        public DateTime? FrmUd6Date { get; set; }
        public DateTime? FrmUd7Date { get; set; }
        public DateTime? FrmUd8Date { get; set; }
        public DateTime? FrmUd9Date { get; set; }
        public DateTime? FrmUd10Date { get; set; }
        public Guid? FrmUd1Id { get; set; }
        public Guid? FrmUd2Id { get; set; }
        public Guid? FrmUd3Id { get; set; }
        public Guid? FrmUd4Id { get; set; }
        public Guid? FrmUd5Id { get; set; }
        public Guid? FrmUd6Id { get; set; }
        public Guid? FrmUd7Id { get; set; }
        public Guid? FrmUd8Id { get; set; }
        public Guid? FrmUd9Id { get; set; }
        public Guid? FrmUd10Id { get; set; }
        public bool? FrmUd1Bit { get; set; }
        public bool? FrmUd2Bit { get; set; }
        public bool? FrmUd3Bit { get; set; }
        public bool? FrmUd4Bit { get; set; }
        public bool? FrmUd5Bit { get; set; }
        public bool? FrmUd6Bit { get; set; }
        public bool? FrmUd7Bit { get; set; }
        public bool? FrmUd8Bit { get; set; }
        public bool? FrmUd9Bit { get; set; }
        public bool? FrmUd10Bit { get; set; }
        public bool? FrmUd11Bit { get; set; }
        public bool? FrmUd12Bit { get; set; }
        public bool? FrmUd13Bit { get; set; }
        public bool? FrmUd14Bit { get; set; }
        public bool? FrmUd15Bit { get; set; }
        public bool? FrmUd16Bit { get; set; }
        public bool? FrmUd17Bit { get; set; }
        public bool? FrmUd18Bit { get; set; }
        public bool? FrmUd19Bit { get; set; }
        public bool? FrmUd20Bit { get; set; }
        public bool? FrmUd21Bit { get; set; }
        public bool? FrmUd22Bit { get; set; }
        public bool? FrmUd23Bit { get; set; }
        public bool? FrmUd24Bit { get; set; }
        public decimal? FrmUd1Numeric { get; set; }
        public decimal? FrmUd2Numeric { get; set; }
        public decimal? FrmUd3Numeric { get; set; }
        public decimal? FrmUd4Numeric { get; set; }
        public decimal? FrmUd5Numeric { get; set; }
        public decimal? FrmUd6Numeric { get; set; }
        public decimal? FrmUd7Numeric { get; set; }
        public decimal? FrmUd8Numeric { get; set; }
        public decimal? FrmUd9Numeric { get; set; }
        public decimal? FrmUd10Numeric { get; set; }
        public string FrmExternal { get; set; }
        public Guid? FrmAcId { get; set; }
        public bool? FrmProcessed { get; set; }
        public byte? FrmSecurity { get; set; }
    }
}
