using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VAccountActivitiesAll
    {
        public Guid? AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid? MacId { get; set; }
        public Guid? OpId { get; set; }
        public Guid? PjId { get; set; }
        public Guid Id { get; set; }
        public Guid? ParentId { get; set; }
        public string ParentSummary { get; set; }
        public bool? ActDeleted { get; set; }
        public bool? ActReadOnly { get; set; }
        public bool? AcaReadonly { get; set; }
        public bool? AccaReadonly { get; set; }
        public bool? OpaReadonly { get; set; }
        public bool? PjaReadonly { get; set; }
        public Guid? UsId { get; set; }
        public string UsName { get; set; }
        public Guid? UsgId { get; set; }
        public string UsgName { get; set; }
        public string Parent { get; set; }
        public Guid? Type { get; set; }
        public string ActivityType { get; set; }
        public string ActivityTypeHlight { get; set; }
        public Guid? AccaStage { get; set; }
        public string Duration { get; set; }
        public string Summary { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? DateCompleted { get; set; }
        public double PercentComplete { get; set; }
        public bool Complete { get; set; }
        public string BillingInformation { get; set; }
        public string Priority { get; set; }
        public string PriorityHlight { get; set; }
        public byte Sensitivity { get; set; }
        public string Status { get; set; }
        public string StatusHlight { get; set; }
        public bool Private { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public Guid? AcUd1Id { get; set; }
        public Guid? AcUd2Id { get; set; }
        public Guid? AcUd3Id { get; set; }
        public Guid? AcUd4Id { get; set; }
        public Guid? AcUd5Id { get; set; }
        public Guid? AcUd6Id { get; set; }
        public Guid? AcUd7Id { get; set; }
        public Guid? AcUd8Id { get; set; }
        public Guid? AcUd9Id { get; set; }
        public Guid? AcUd10Id { get; set; }
        public string AcaUd1Text { get; set; }
        public string AcaUd2Text { get; set; }
        public string AcaUd3Text { get; set; }
        public string AcaUd4Text { get; set; }
        public string AcaUd5Text { get; set; }
        public string AcaUd6Text { get; set; }
        public string AcaUd7Text { get; set; }
        public string AcaUd8Text { get; set; }
        public string AcaUd9Text { get; set; }
        public string AcaUd10Text { get; set; }
        public DateTime? AcaUd1Date { get; set; }
        public DateTime? AcaUd2Date { get; set; }
        public DateTime? AcaUd3Date { get; set; }
        public DateTime? AcaUd4Date { get; set; }
        public DateTime? AcaUd5Date { get; set; }
        public DateTime? AcaUd6Date { get; set; }
        public DateTime? AcaUd7Date { get; set; }
        public DateTime? AcaUd8Date { get; set; }
        public DateTime? AcaUd9Date { get; set; }
        public DateTime? AcaUd10Date { get; set; }
        public Guid? AcaUd1Id { get; set; }
        public Guid? AcaUd2Id { get; set; }
        public Guid? AcaUd3Id { get; set; }
        public Guid? AcaUd4Id { get; set; }
        public Guid? AcaUd5Id { get; set; }
        public Guid? AcaUd6Id { get; set; }
        public Guid? AcaUd7Id { get; set; }
        public Guid? AcaUd8Id { get; set; }
        public Guid? AcaUd9Id { get; set; }
        public Guid? AcaUd10Id { get; set; }
        public bool? AcaUd1Bit { get; set; }
        public bool? AcaUd2Bit { get; set; }
        public bool? AcaUd3Bit { get; set; }
        public bool? AcaUd4Bit { get; set; }
        public bool? AcaUd5Bit { get; set; }
        public bool? AcaUd6Bit { get; set; }
        public bool? AcaUd7Bit { get; set; }
        public bool? AcaUd8Bit { get; set; }
        public bool? AcaUd9Bit { get; set; }
        public bool? AcaUd10Bit { get; set; }
        public decimal? AcaUd1Numeric { get; set; }
        public decimal? AcaUd2Numeric { get; set; }
        public decimal? AcaUd3Numeric { get; set; }
        public decimal? AcaUd4Numeric { get; set; }
        public decimal? AcaUd5Numeric { get; set; }
        public decimal? AcaUd6Numeric { get; set; }
        public decimal? AcaUd7Numeric { get; set; }
        public decimal? AcaUd8Numeric { get; set; }
        public decimal? AcaUd9Numeric { get; set; }
        public decimal? AcaUd10Numeric { get; set; }
        public string AccaUd1Text { get; set; }
        public string AccaUd2Text { get; set; }
        public string AccaUd3Text { get; set; }
        public string AccaUd4Text { get; set; }
        public string AccaUd5Text { get; set; }
        public string AccaUd6Text { get; set; }
        public string AccaUd7Text { get; set; }
        public string AccaUd8Text { get; set; }
        public string AccaUd9Text { get; set; }
        public string AccaUd10Text { get; set; }
        public DateTime? AccaUd1Date { get; set; }
        public DateTime? AccaUd2Date { get; set; }
        public DateTime? AccaUd3Date { get; set; }
        public DateTime? AccaUd4Date { get; set; }
        public DateTime? AccaUd5Date { get; set; }
        public DateTime? AccaUd6Date { get; set; }
        public DateTime? AccaUd7Date { get; set; }
        public DateTime? AccaUd8Date { get; set; }
        public DateTime? AccaUd9Date { get; set; }
        public DateTime? AccaUd10Date { get; set; }
        public Guid? AccaUd1Id { get; set; }
        public Guid? AccaUd2Id { get; set; }
        public Guid? AccaUd3Id { get; set; }
        public Guid? AccaUd4Id { get; set; }
        public Guid? AccaUd5Id { get; set; }
        public Guid? AccaUd6Id { get; set; }
        public Guid? AccaUd7Id { get; set; }
        public Guid? AccaUd8Id { get; set; }
        public Guid? AccaUd9Id { get; set; }
        public Guid? AccaUd10Id { get; set; }
        public bool? AccaUd1Bit { get; set; }
        public bool? AccaUd2Bit { get; set; }
        public bool? AccaUd3Bit { get; set; }
        public bool? AccaUd4Bit { get; set; }
        public bool? AccaUd5Bit { get; set; }
        public bool? AccaUd6Bit { get; set; }
        public bool? AccaUd7Bit { get; set; }
        public bool? AccaUd8Bit { get; set; }
        public bool? AccaUd9Bit { get; set; }
        public bool? AccaUd10Bit { get; set; }
        public decimal? AccaUd1Numeric { get; set; }
        public decimal? AccaUd2Numeric { get; set; }
        public decimal? AccaUd3Numeric { get; set; }
        public decimal? AccaUd4Numeric { get; set; }
        public decimal? AccaUd5Numeric { get; set; }
        public decimal? AccaUd6Numeric { get; set; }
        public decimal? AccaUd7Numeric { get; set; }
        public decimal? AccaUd8Numeric { get; set; }
        public decimal? AccaUd9Numeric { get; set; }
        public decimal? AccaUd10Numeric { get; set; }
        public string OpaUd1Text { get; set; }
        public string OpaUd2Text { get; set; }
        public string OpaUd3Text { get; set; }
        public string OpaUd4Text { get; set; }
        public string OpaUd5Text { get; set; }
        public string OpaUd6Text { get; set; }
        public string OpaUd7Text { get; set; }
        public string OpaUd8Text { get; set; }
        public string OpaUd9Text { get; set; }
        public string OpaUd10Text { get; set; }
        public DateTime? OpaUd1Date { get; set; }
        public DateTime? OpaUd2Date { get; set; }
        public DateTime? OpaUd3Date { get; set; }
        public DateTime? OpaUd4Date { get; set; }
        public DateTime? OpaUd5Date { get; set; }
        public DateTime? OpaUd6Date { get; set; }
        public DateTime? OpaUd7Date { get; set; }
        public DateTime? OpaUd8Date { get; set; }
        public DateTime? OpaUd9Date { get; set; }
        public DateTime? OpaUd10Date { get; set; }
        public Guid? OpaUd1Id { get; set; }
        public Guid? OpaUd2Id { get; set; }
        public Guid? OpaUd3Id { get; set; }
        public Guid? OpaUd4Id { get; set; }
        public Guid? OpaUd5Id { get; set; }
        public Guid? OpaUd6Id { get; set; }
        public Guid? OpaUd7Id { get; set; }
        public Guid? OpaUd8Id { get; set; }
        public Guid? OpaUd9Id { get; set; }
        public Guid? OpaUd10Id { get; set; }
        public bool? OpaUd1Bit { get; set; }
        public bool? OpaUd2Bit { get; set; }
        public bool? OpaUd3Bit { get; set; }
        public bool? OpaUd4Bit { get; set; }
        public bool? OpaUd5Bit { get; set; }
        public bool? OpaUd6Bit { get; set; }
        public bool? OpaUd7Bit { get; set; }
        public bool? OpaUd8Bit { get; set; }
        public bool? OpaUd9Bit { get; set; }
        public bool? OpaUd10Bit { get; set; }
        public decimal? OpaUd1Numeric { get; set; }
        public decimal? OpaUd2Numeric { get; set; }
        public decimal? OpaUd3Numeric { get; set; }
        public decimal? OpaUd4Numeric { get; set; }
        public decimal? OpaUd5Numeric { get; set; }
        public decimal? OpaUd6Numeric { get; set; }
        public decimal? OpaUd7Numeric { get; set; }
        public decimal? OpaUd8Numeric { get; set; }
        public decimal? OpaUd9Numeric { get; set; }
        public decimal? OpaUd10Numeric { get; set; }
        public string PjaUd1Text { get; set; }
        public string PjaUd2Text { get; set; }
        public string PjaUd3Text { get; set; }
        public string PjaUd4Text { get; set; }
        public string PjaUd5Text { get; set; }
        public string PjaUd6Text { get; set; }
        public string PjaUd7Text { get; set; }
        public string PjaUd8Text { get; set; }
        public string PjaUd9Text { get; set; }
        public string PjaUd10Text { get; set; }
        public DateTime? PjaUd1Date { get; set; }
        public DateTime? PjaUd2Date { get; set; }
        public DateTime? PjaUd3Date { get; set; }
        public DateTime? PjaUd4Date { get; set; }
        public DateTime? PjaUd5Date { get; set; }
        public DateTime? PjaUd6Date { get; set; }
        public DateTime? PjaUd7Date { get; set; }
        public DateTime? PjaUd8Date { get; set; }
        public DateTime? PjaUd9Date { get; set; }
        public DateTime? PjaUd10Date { get; set; }
        public Guid? PjaUd1Id { get; set; }
        public Guid? PjaUd2Id { get; set; }
        public Guid? PjaUd3Id { get; set; }
        public Guid? PjaUd4Id { get; set; }
        public Guid? PjaUd5Id { get; set; }
        public Guid? PjaUd6Id { get; set; }
        public Guid? PjaUd7Id { get; set; }
        public Guid? PjaUd8Id { get; set; }
        public Guid? PjaUd9Id { get; set; }
        public Guid? PjaUd10Id { get; set; }
        public bool? PjaUd1Bit { get; set; }
        public bool? PjaUd2Bit { get; set; }
        public bool? PjaUd3Bit { get; set; }
        public bool? PjaUd4Bit { get; set; }
        public bool? PjaUd5Bit { get; set; }
        public bool? PjaUd6Bit { get; set; }
        public bool? PjaUd7Bit { get; set; }
        public bool? PjaUd8Bit { get; set; }
        public bool? PjaUd9Bit { get; set; }
        public bool? PjaUd10Bit { get; set; }
        public decimal? PjaUd1Numeric { get; set; }
        public decimal? PjaUd2Numeric { get; set; }
        public decimal? PjaUd3Numeric { get; set; }
        public decimal? PjaUd4Numeric { get; set; }
        public decimal? PjaUd5Numeric { get; set; }
        public decimal? PjaUd6Numeric { get; set; }
        public decimal? PjaUd7Numeric { get; set; }
        public decimal? PjaUd8Numeric { get; set; }
        public decimal? PjaUd9Numeric { get; set; }
        public decimal? PjaUd10Numeric { get; set; }
        public string ActExternal { get; set; }
        public string AcaExternal { get; set; }
        public string AccaExternal { get; set; }
        public string OpaExternal { get; set; }
        public string PjaExternal { get; set; }
        public Guid? AcaImport { get; set; }
        public string ImSummary { get; set; }
        public bool Exported { get; set; }
        public int? AccaNumber { get; set; }
        public Guid? McrId { get; set; }
        public string Reference { get; set; }
        public bool? Reminder { get; set; }
        public int? ReminderMinutes { get; set; }
        public string ReminderMinutesName { get; set; }
        public bool? ReminderAlerted { get; set; }
        public bool? ShowOnCalendar { get; set; }
        public Guid? StgId { get; set; }
        public int Overdue { get; set; }
        public int? DaysOpen { get; set; }
        public string AcaUd1IdName { get; set; }
        public string AcaUd2IdName { get; set; }
        public string AcaUd3IdName { get; set; }
        public string AcaUd4IdName { get; set; }
        public string AcaUd5IdName { get; set; }
        public string AcaUd6IdName { get; set; }
        public string AcaUd7IdName { get; set; }
        public string AcaUd8IdName { get; set; }
        public string AcaUd9IdName { get; set; }
        public string AcaUd10IdName { get; set; }
        public string AccaUd1IdName { get; set; }
        public string AccaUd2IdName { get; set; }
        public string AccaUd3IdName { get; set; }
        public string AccaUd4IdName { get; set; }
        public string AccaUd5IdName { get; set; }
        public string AccaUd6IdName { get; set; }
        public string AccaUd7IdName { get; set; }
        public string AccaUd8IdName { get; set; }
        public string AccaUd9IdName { get; set; }
        public string AccaUd10IdName { get; set; }
        public string OpaUd1IdName { get; set; }
        public string OpaUd2IdName { get; set; }
        public string OpaUd3IdName { get; set; }
        public string OpaUd4IdName { get; set; }
        public string OpaUd5IdName { get; set; }
        public string OpaUd6IdName { get; set; }
        public string OpaUd7IdName { get; set; }
        public string OpaUd8IdName { get; set; }
        public string OpaUd9IdName { get; set; }
        public string OpaUd10IdName { get; set; }
        public string PjaUd1IdName { get; set; }
        public string PjaUd2IdName { get; set; }
        public string PjaUd3IdName { get; set; }
        public string PjaUd4IdName { get; set; }
        public string PjaUd5IdName { get; set; }
        public string PjaUd6IdName { get; set; }
        public string PjaUd7IdName { get; set; }
        public string PjaUd8IdName { get; set; }
        public string PjaUd9IdName { get; set; }
        public string PjaUd10IdName { get; set; }
        public string AcaUd1IdNameHlight { get; set; }
        public string AcaUd2IdNameHlight { get; set; }
        public string AcaUd3IdNameHlight { get; set; }
        public string AcaUd4IdNameHlight { get; set; }
        public string AcaUd5IdNameHlight { get; set; }
        public string AcaUd6IdNameHlight { get; set; }
        public string AcaUd7IdNameHlight { get; set; }
        public string AcaUd8IdNameHlight { get; set; }
        public string AcaUd9IdNameHlight { get; set; }
        public string AcaUd10IdNameHlight { get; set; }
        public string AccaUd1IdNameHlight { get; set; }
        public string AccaUd2IdNameHlight { get; set; }
        public string AccaUd3IdNameHlight { get; set; }
        public string AccaUd4IdNameHlight { get; set; }
        public string AccaUd5IdNameHlight { get; set; }
        public string AccaUd6IdNameHlight { get; set; }
        public string AccaUd7IdNameHlight { get; set; }
        public string AccaUd8IdNameHlight { get; set; }
        public string AccaUd9IdNameHlight { get; set; }
        public string AccaUd10IdNameHlight { get; set; }
        public string OpaUd1IdNameHlight { get; set; }
        public string OpaUd2IdNameHlight { get; set; }
        public string OpaUd3IdNameHlight { get; set; }
        public string OpaUd4IdNameHlight { get; set; }
        public string OpaUd5IdNameHlight { get; set; }
        public string OpaUd6IdNameHlight { get; set; }
        public string OpaUd7IdNameHlight { get; set; }
        public string OpaUd8IdNameHlight { get; set; }
        public string OpaUd9IdNameHlight { get; set; }
        public string OpaUd10IdNameHlight { get; set; }
        public string PjaUd1IdNameHlight { get; set; }
        public string PjaUd2IdNameHlight { get; set; }
        public string PjaUd3IdNameHlight { get; set; }
        public string PjaUd4IdNameHlight { get; set; }
        public string PjaUd5IdNameHlight { get; set; }
        public string PjaUd6IdNameHlight { get; set; }
        public string PjaUd7IdNameHlight { get; set; }
        public string PjaUd8IdNameHlight { get; set; }
        public string PjaUd9IdNameHlight { get; set; }
        public string PjaUd10IdNameHlight { get; set; }
        public string AcName { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string AcType { get; set; }
        public string AcType2 { get; set; }
        public string AcTypeHlight { get; set; }
        public string AcType2Hlight { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AccountManager { get; set; }
        public string AccountManagerEmail { get; set; }
        public string AcPhone1 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcCountry { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcReference { get; set; }
        public string ContactName { get; set; }
        public string AccName { get; set; }
        public string AccBusinessTelephonenumber { get; set; }
        public string AccEmail1Address { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public string MacStage { get; set; }
        public string MacStageHlight { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string SemName { get; set; }
        public Guid? SemId { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string AcExternal { get; set; }
        public string OpStage { get; set; }
        public string PjStage { get; set; }
        public string OpState { get; set; }
        public Guid? SecurityId { get; set; }
        public string SecurityGroup { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public Guid AcaId { get; set; }
        public Guid AccaId { get; set; }
        public Guid OpaId { get; set; }
        public Guid PjaId { get; set; }
        public byte SensitivityId { get; set; }
        public byte StatusId { get; set; }
        public byte PriorityId { get; set; }
        public string ParentName { get; set; }
        public string Details { get; set; }
    }
}
