using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VAccountsProfile
    {
        public Guid? AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid AcpId { get; set; }
        public bool? AcpDeleted { get; set; }
        public Guid? Type { get; set; }
        public Guid? Label { get; set; }
        public string Summary { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string AcpUd1Text { get; set; }
        public string AcpUd2Text { get; set; }
        public string AcpUd3Text { get; set; }
        public string AcpUd4Text { get; set; }
        public string AcpUd5Text { get; set; }
        public string AcpUd6Text { get; set; }
        public string AcpUd7Text { get; set; }
        public string AcpUd8Text { get; set; }
        public string AcpUd9Text { get; set; }
        public string AcpUd10Text { get; set; }
        public DateTime? AcpUd1Date { get; set; }
        public DateTime? AcpUd2Date { get; set; }
        public DateTime? AcpUd3Date { get; set; }
        public DateTime? AcpUd4Date { get; set; }
        public DateTime? AcpUd5Date { get; set; }
        public DateTime? AcpUd6Date { get; set; }
        public DateTime? AcpUd7Date { get; set; }
        public DateTime? AcpUd8Date { get; set; }
        public DateTime? AcpUd9Date { get; set; }
        public DateTime? AcpUd10Date { get; set; }
        public Guid? AcpUd1Id { get; set; }
        public Guid? AcpUd2Id { get; set; }
        public Guid? AcpUd3Id { get; set; }
        public Guid? AcpUd4Id { get; set; }
        public Guid? AcpUd5Id { get; set; }
        public Guid? AcpUd6Id { get; set; }
        public Guid? AcpUd7Id { get; set; }
        public Guid? AcpUd8Id { get; set; }
        public Guid? AcpUd9Id { get; set; }
        public Guid? AcpUd10Id { get; set; }
        public bool? AcpUd1Bit { get; set; }
        public bool? AcpUd2Bit { get; set; }
        public bool? AcpUd3Bit { get; set; }
        public bool? AcpUd4Bit { get; set; }
        public bool? AcpUd5Bit { get; set; }
        public bool? AcpUd6Bit { get; set; }
        public bool? AcpUd7Bit { get; set; }
        public bool? AcpUd8Bit { get; set; }
        public bool? AcpUd9Bit { get; set; }
        public bool? AcpUd10Bit { get; set; }
        public bool? AcpUd11Bit { get; set; }
        public bool? AcpUd12Bit { get; set; }
        public bool? AcpUd13Bit { get; set; }
        public bool? AcpUd14Bit { get; set; }
        public bool? AcpUd15Bit { get; set; }
        public bool? AcpUd16Bit { get; set; }
        public bool? AcpUd17Bit { get; set; }
        public bool? AcpUd18Bit { get; set; }
        public bool? AcpUd19Bit { get; set; }
        public bool? AcpUd20Bit { get; set; }
        public bool? AcpUd21Bit { get; set; }
        public bool? AcpUd22Bit { get; set; }
        public bool? AcpUd23Bit { get; set; }
        public bool? AcpUd24Bit { get; set; }
        public decimal? AcpUd1Numeric { get; set; }
        public decimal? AcpUd2Numeric { get; set; }
        public decimal? AcpUd3Numeric { get; set; }
        public decimal? AcpUd4Numeric { get; set; }
        public decimal? AcpUd5Numeric { get; set; }
        public decimal? AcpUd6Numeric { get; set; }
        public decimal? AcpUd7Numeric { get; set; }
        public decimal? AcpUd8Numeric { get; set; }
        public decimal? AcpUd9Numeric { get; set; }
        public decimal? AcpUd10Numeric { get; set; }
        public string AcpExternal { get; set; }
        public Guid? AcpImport { get; set; }
        public string Reference { get; set; }
        public Guid? SitId { get; set; }
        public string SitName { get; set; }
        public string ProfileType { get; set; }
        public string ProfileTypeDetails { get; set; }
        public string ProfileLabel { get; set; }
        public string ProfileTypeHlight { get; set; }
        public string ProfileLabelHlight { get; set; }
        public string AccName { get; set; }
        public string AcpUd1IdName { get; set; }
        public string AcpUd2IdName { get; set; }
        public string AcpUd3IdName { get; set; }
        public string AcpUd4IdName { get; set; }
        public string AcpUd5IdName { get; set; }
        public string AcpUd6IdName { get; set; }
        public string AcpUd7IdName { get; set; }
        public string AcpUd8IdName { get; set; }
        public string AcpUd9IdName { get; set; }
        public string AcpUd10IdName { get; set; }
        public string AcpUd1IdNameHlight { get; set; }
        public string AcpUd2IdNameHlight { get; set; }
        public string AcpUd3IdNameHlight { get; set; }
        public string AcpUd4IdNameHlight { get; set; }
        public string AcpUd5IdNameHlight { get; set; }
        public string AcpUd6IdNameHlight { get; set; }
        public string AcpUd7IdNameHlight { get; set; }
        public string AcpUd8IdNameHlight { get; set; }
        public string AcpUd9IdNameHlight { get; set; }
        public string AcpUd10IdNameHlight { get; set; }
        public string AcName { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AcManager { get; set; }
        public string AcManagerEmail { get; set; }
        public string AcPhone1 { get; set; }
        public string AcAddress1 { get; set; }
        public string AcAddress2 { get; set; }
        public string AcAddress3 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcCountry { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcReference { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcType1 { get; set; }
        public string AcType2 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2Hlight { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public Guid? AcUd10Id { get; set; }
        public Guid? AcUd1Id { get; set; }
        public Guid? AcUd2Id { get; set; }
        public Guid? AcUd3Id { get; set; }
        public Guid? AcUd4Id { get; set; }
        public Guid? AcUd5Id { get; set; }
        public Guid? AcUd6Id { get; set; }
        public Guid? AcUd7Id { get; set; }
        public Guid? AcUd8Id { get; set; }
        public Guid? AcUd9Id { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string BusinessTelephoneNumber { get; set; }
        public string Email1Address { get; set; }
        public string HomeTelephoneNumber { get; set; }
        public string MobileTelephoneNumber { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public string ImSummary { get; set; }
        public string ShortCode { get; set; }
    }
}
