using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VContactsLinked
    {
        public Guid? AcId { get; set; }
        public Guid AccId { get; set; }
        public bool? AccDeleted { get; set; }
        public string Summary { get; set; }
        public string Account { get; set; }
        public string Anniversary { get; set; }
        public string Assistantname { get; set; }
        public string AssistantTelephoneNumber { get; set; }
        public string Birthday { get; set; }
        public string BillingInformation { get; set; }
        public string Business2TelephoneNumber { get; set; }
        public string BusinessAddress { get; set; }
        public string BusinessAddressCity { get; set; }
        public string BusinessAddressCountry { get; set; }
        public string BusinessAddressPostalCode { get; set; }
        public string BusinessAddressPostOfficeBox { get; set; }
        public string BusinessAddressState { get; set; }
        public string BusinessAddressStreet { get; set; }
        public string BusinessAddressStreet2 { get; set; }
        public string BusinessAddressStreet3 { get; set; }
        public string BusinessFaxNumber { get; set; }
        public string BusinessFaxNumberFormatted { get; set; }
        public string BusinessHomePage { get; set; }
        public string BusinessTelephoneNumber { get; set; }
        public string CallbackTelephoneNumber { get; set; }
        public string CarTelephoneNumber { get; set; }
        public string Categories { get; set; }
        public string Children { get; set; }
        public string Companies { get; set; }
        public string CompanyAndFullName { get; set; }
        public string CompanyLastFirstNoSpace { get; set; }
        public string CompanyLastFirstSpaceOnly { get; set; }
        public string CompanyMainTelephoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string ComputerNetworkName { get; set; }
        public string CreationTime { get; set; }
        public string Department { get; set; }
        public string Email1Address { get; set; }
        public string Email1AddressType { get; set; }
        public string Email1DisplayName { get; set; }
        public string Email1EntryId { get; set; }
        public string Email2Address { get; set; }
        public string Email2AddressType { get; set; }
        public string Email2DisplayName { get; set; }
        public string Email2EntryId { get; set; }
        public string Email3Address { get; set; }
        public string Email3AddressType { get; set; }
        public string Email3DisplayName { get; set; }
        public string Email3EntryId { get; set; }
        public string FirstName { get; set; }
        public string Ftpsite { get; set; }
        public string FullName { get; set; }
        public string FullNameAndCompany { get; set; }
        public string Hobby { get; set; }
        public string Home2TelephoneNumber { get; set; }
        public string HomeAddress { get; set; }
        public string HomeAddressCity { get; set; }
        public string HomeAddressCountry { get; set; }
        public string HomeAddressPostalCode { get; set; }
        public string HomeAddressPostOfficeBox { get; set; }
        public string HomeAddressState { get; set; }
        public string HomeAddressStreet { get; set; }
        public string HomeAddressStreet2 { get; set; }
        public string HomeAddressStreet3 { get; set; }
        public string HomeFaxNumber { get; set; }
        public string HomeFaxNumberFormatted { get; set; }
        public string HomeTelephoneNumber { get; set; }
        public string Initials { get; set; }
        public string InternetFreeBusyAddress { get; set; }
        public string Isdnnumber { get; set; }
        public string JobTitle { get; set; }
        public string LastFirstAndSuffix { get; set; }
        public string LastFirstNoSpaceCompany { get; set; }
        public string LastFirstSpaceOnly { get; set; }
        public string LastFirstSpaceOnlyCompany { get; set; }
        public string LastModificationTime { get; set; }
        public string LastName { get; set; }
        public string LastNameAndFirstName { get; set; }
        public string MailingAddress { get; set; }
        public string MailingAddressCity { get; set; }
        public string MailingAddressCountry { get; set; }
        public string MailingAddressPostalCode { get; set; }
        public string MailingAddressPostOfficeBox { get; set; }
        public string MailingAddressState { get; set; }
        public string MailingAddressStreet { get; set; }
        public string MailingAddressStreet2 { get; set; }
        public string MailingAddressStreet3 { get; set; }
        public string ManagerName { get; set; }
        public string MiddleName { get; set; }
        public string Mileage { get; set; }
        public string MobileTelephoneNumber { get; set; }
        public string NetMeetingAlias { get; set; }
        public string NetMeetingServer { get; set; }
        public string NickName { get; set; }
        public string OfficeLocation { get; set; }
        public string OtherAddress { get; set; }
        public string OtherAddressCity { get; set; }
        public string OtherAddressCountry { get; set; }
        public string OtherAddressPostalCode { get; set; }
        public string OtherAddressPostOfficeBox { get; set; }
        public string OtherAddressState { get; set; }
        public string OtherAddressStreet { get; set; }
        public string OtherAddressStreet2 { get; set; }
        public string OtherAddressStreet3 { get; set; }
        public string OtherFaxNumber { get; set; }
        public string OtherTelephoneNumber { get; set; }
        public string PersonalHomePage { get; set; }
        public string PrimaryTelephoneNumber { get; set; }
        public string Profession { get; set; }
        public string RadioTelephoneNumber { get; set; }
        public string ReferredBy { get; set; }
        public string SelectedMailingAddress { get; set; }
        public string Sensitivity { get; set; }
        public string Spouse { get; set; }
        public string Subject { get; set; }
        public string Suffix { get; set; }
        public string TelexNumber { get; set; }
        public string Title { get; set; }
        public string TtytddtelephoneNumber { get; set; }
        public string WebPage { get; set; }
        public string YomiCompanyName { get; set; }
        public string YomiFirstName { get; set; }
        public string YomiLastName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string AccExternal { get; set; }
        public Guid? AccImport { get; set; }
        public int? PreferredContact { get; set; }
        public bool Exported { get; set; }
        public string Salutation { get; set; }
        public string AccUd1 { get; set; }
        public string AccUd2 { get; set; }
        public string AccUd3 { get; set; }
        public string AccUd4 { get; set; }
        public string AccUd5 { get; set; }
        public string AccUd6 { get; set; }
        public string AccUd7 { get; set; }
        public string AccUd8 { get; set; }
        public string AccUd9 { get; set; }
        public string AccUd10 { get; set; }
        public string AccUd11 { get; set; }
        public string AccUd12 { get; set; }
        public string AccUd13 { get; set; }
        public string AccUd14 { get; set; }
        public string AccUd15 { get; set; }
        public Guid? AccUd1Id { get; set; }
        public Guid? AccUd2Id { get; set; }
        public Guid? AccUd3Id { get; set; }
        public Guid? AccUd4Id { get; set; }
        public Guid? AccUd5Id { get; set; }
        public Guid? AccUd6Id { get; set; }
        public Guid? AccUd7Id { get; set; }
        public Guid? AccUd8Id { get; set; }
        public Guid? AccUd9Id { get; set; }
        public Guid? AccUd10Id { get; set; }
        public DateTime? AccUd1Date { get; set; }
        public DateTime? AccUd2Date { get; set; }
        public DateTime? AccUd3Date { get; set; }
        public DateTime? AccUd4Date { get; set; }
        public DateTime? AccUd5Date { get; set; }
        public DateTime? AccUd6Date { get; set; }
        public DateTime? AccUd7Date { get; set; }
        public DateTime? AccUd8Date { get; set; }
        public DateTime? AccUd9Date { get; set; }
        public DateTime? AccUd10Date { get; set; }
        public bool? AccUd1Bit { get; set; }
        public bool? AccUd2Bit { get; set; }
        public bool? AccUd3Bit { get; set; }
        public bool? AccUd4Bit { get; set; }
        public bool? AccUd5Bit { get; set; }
        public bool? AccUd6Bit { get; set; }
        public bool? AccUd7Bit { get; set; }
        public bool? AccUd8Bit { get; set; }
        public bool? AccUd9Bit { get; set; }
        public bool? AccUd10Bit { get; set; }
        public bool? AccUd11Bit { get; set; }
        public bool? AccUd12Bit { get; set; }
        public bool? AccUd13Bit { get; set; }
        public bool? AccUd14Bit { get; set; }
        public bool? AccUd15Bit { get; set; }
        public bool? AccUd16Bit { get; set; }
        public bool? AccUd17Bit { get; set; }
        public bool? AccUd18Bit { get; set; }
        public bool? AccUd19Bit { get; set; }
        public bool? AccUd20Bit { get; set; }
        public bool? AccUd21Bit { get; set; }
        public bool? AccUd22Bit { get; set; }
        public bool? AccUd23Bit { get; set; }
        public bool? AccUd24Bit { get; set; }
        public decimal? AccUd1Numeric { get; set; }
        public decimal? AccUd2Numeric { get; set; }
        public decimal? AccUd3Numeric { get; set; }
        public decimal? AccUd4Numeric { get; set; }
        public decimal? AccUd5Numeric { get; set; }
        public decimal? AccUd6Numeric { get; set; }
        public decimal? AccUd7Numeric { get; set; }
        public decimal? AccUd8Numeric { get; set; }
        public decimal? AccUd9Numeric { get; set; }
        public decimal? AccUd10Numeric { get; set; }
        public bool? PreferredContactEmail { get; set; }
        public bool? PreferredContactFax { get; set; }
        public bool? PreferredContactPhone { get; set; }
        public bool? PreferredContactLetter { get; set; }
        public string Reference { get; set; }
        public bool? PrivacyNotified { get; set; }
        public DateTime? PrivacyNotifiedDate { get; set; }
        public string PrivacyNotifiedBy { get; set; }
        public string PrivacyNotifiedMethod { get; set; }
        public Guid? UsId { get; set; }
        public string UsName { get; set; }
        public string UsgName { get; set; }
        public byte? PrefPhone { get; set; }
        public byte? PrefAddress { get; set; }
        public byte? PrefEmail { get; set; }
        public Guid? AccStatus { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public bool? ConnectOptIn { get; set; }
        public DateTime? ConnectOptInDate { get; set; }
        public int PrimaryContact { get; set; }
        public string AccUd1IdName { get; set; }
        public string AccUd2IdName { get; set; }
        public string AccUd3IdName { get; set; }
        public string AccUd4IdName { get; set; }
        public string AccUd5IdName { get; set; }
        public string AccUd6IdName { get; set; }
        public string AccUd7IdName { get; set; }
        public string AccUd8IdName { get; set; }
        public string AccUd9IdName { get; set; }
        public string AccUd10IdName { get; set; }
        public string AccUd1IdNameHlight { get; set; }
        public string AccUd2IdNameHlight { get; set; }
        public string AccUd3IdNameHlight { get; set; }
        public string AccUd4IdNameHlight { get; set; }
        public string AccUd5IdNameHlight { get; set; }
        public string AccUd6IdNameHlight { get; set; }
        public string AccUd7IdNameHlight { get; set; }
        public string AccUd8IdNameHlight { get; set; }
        public string AccUd9IdNameHlight { get; set; }
        public string AccUd10IdNameHlight { get; set; }
        public string Status { get; set; }
        public string State { get; set; }
        public string ImSummary { get; set; }
        public string AccountName { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string AcType { get; set; }
        public string AcType2 { get; set; }
        public string AcTypeHlight { get; set; }
        public string AcType2Hlight { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AcManager { get; set; }
        public string AcManagerEmail { get; set; }
        public string AcManagerDept { get; set; }
        public string AcManagerGroup { get; set; }
        public string AcPhone1 { get; set; }
        public string AcAddress1 { get; set; }
        public string AcAddress2 { get; set; }
        public string AcAddress3 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcBillingAddress1 { get; set; }
        public string AcBillingAddress2 { get; set; }
        public string AcBillingAddress3 { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcReference { get; set; }
        public string AcExternal { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string LinkedinPublicId { get; set; }
        public string LinkedinPrivateId { get; set; }
        public string LinkedinProfileUrl { get; set; }
        public string LinkedinImage { get; set; }
        public string LinkedinName { get; set; }
        public string FacebookPublicId { get; set; }
        public string FacebookPrivateId { get; set; }
        public string FacebookProfileUrl { get; set; }
        public string FacebookImage { get; set; }
        public string FacebookName { get; set; }
        public string GplusPublicId { get; set; }
        public string GplusPrivateId { get; set; }
        public string GplusProfileUrl { get; set; }
        public string GplusImage { get; set; }
        public string GplusName { get; set; }
        public string Twitter1PublicId { get; set; }
        public string Twitter1PrivateId { get; set; }
        public string Twitter1ProfileUrl { get; set; }
        public string Twitter1Image { get; set; }
        public string Twitter1Name { get; set; }
        public string Twitter2PublicId { get; set; }
        public string Twitter2PrivateId { get; set; }
        public string Twitter2ProfileUrl { get; set; }
        public string Twitter2Image { get; set; }
        public string Twitter2Name { get; set; }
        public string Twitter3PublicId { get; set; }
        public string Twitter3PrivateId { get; set; }
        public string Twitter3ProfileUrl { get; set; }
        public string Twitter3Image { get; set; }
        public string Twitter3Name { get; set; }
        public string Twitter4PublicId { get; set; }
        public string Twitter4PrivateId { get; set; }
        public string Twitter4ProfileUrl { get; set; }
        public string Twitter4Image { get; set; }
        public string Twitter4Name { get; set; }
        public string Twitter5PublicId { get; set; }
        public string Twitter5PrivateId { get; set; }
        public string Twitter5ProfileUrl { get; set; }
        public string Twitter5Image { get; set; }
        public string Twitter5Name { get; set; }
        public DateTime? RemovalDate { get; set; }
        public string AccPrefAddress1 { get; set; }
        public string AccPrefAddress2 { get; set; }
        public string AccPrefAddress3 { get; set; }
        public string AccPrefTown { get; set; }
        public string AccPrefCounty { get; set; }
        public string AccPrefPostcode { get; set; }
        public string AccPrefCountry { get; set; }
        public Guid? ParentId { get; set; }
        public string Relationship { get; set; }
    }
}
