using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VDesignDefaultAccountView
    {
        public Guid? AcgId { get; set; }
        public Guid AcId { get; set; }
        public bool? AcDeleted { get; set; }
        public string AcNumber { get; set; }
        public decimal? AcPotential { get; set; }
        public decimal AcDiscount { get; set; }
        public Guid? AcFlag { get; set; }
        public string Name { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public Guid? Type1 { get; set; }
        public Guid? Type2 { get; set; }
        public string Site { get; set; }
        public Guid? Parent { get; set; }
        public Guid? Label { get; set; }
        public Guid? Level { get; set; }
        public Guid? AccIdSales { get; set; }
        public Guid? AccIdSupport { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingTown { get; set; }
        public string BillingCounty { get; set; }
        public string BillingPostcode { get; set; }
        public string BillingCountry { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Fax3 { get; set; }
        public string WebSite1 { get; set; }
        public string WebSite2 { get; set; }
        public Guid? Source { get; set; }
        public Guid? Industry { get; set; }
        public string NumberEmployees { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string AcUd1 { get; set; }
        public string AcUd2 { get; set; }
        public string AcUd3 { get; set; }
        public string AcUd4 { get; set; }
        public string AcUd5 { get; set; }
        public string AcUd6 { get; set; }
        public string AcUd7 { get; set; }
        public string AcUd8 { get; set; }
        public string AcUd9 { get; set; }
        public string AcUd10 { get; set; }
        public string AcUd11 { get; set; }
        public string AcUd12 { get; set; }
        public string AcUd13 { get; set; }
        public string AcUd14 { get; set; }
        public string AcUd15 { get; set; }
        public Guid? AcImport { get; set; }
        public string AcExternal { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public Guid? AcUd1Id { get; set; }
        public Guid? AcUd2Id { get; set; }
        public Guid? AcUd3Id { get; set; }
        public Guid? AcUd4Id { get; set; }
        public Guid? AcUd5Id { get; set; }
        public Guid? AcUd6Id { get; set; }
        public Guid? AcUd7Id { get; set; }
        public Guid? AcUd8Id { get; set; }
        public Guid? AcUd9Id { get; set; }
        public Guid? AcUd10Id { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public bool? AcDormant { get; set; }
        public string Validationmessage { get; set; }
        public string EmailDomains { get; set; }
        public string NameLongestWord { get; set; }
        public string NameSoundex { get; set; }
        public Guid? CurId { get; set; }
        public string Reference { get; set; }
        public int? ReferenceSeed { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public decimal? AcSales { get; set; }
        public string LinkedinName { get; set; }
        public int? CsId { get; set; }
        public string Sentiment { get; set; }
    }
}
