using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VOpportunity
    {
        public Guid AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid OpId { get; set; }
        public bool OpDeleted { get; set; }
        public int? OpNumber { get; set; }
        public Guid? Owner { get; set; }
        public Guid? Stage { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public DateTime? EstimatedClose { get; set; }
        public DateTime? ActualClose { get; set; }
        public Guid? InterestedIn { get; set; }
        public decimal PotentialValue { get; set; }
        public decimal Probability { get; set; }
        public decimal ForecastValue { get; set; }
        public bool? AddToForecast { get; set; }
        public decimal Duration { get; set; }
        public Guid? Source { get; set; }
        public string Type { get; set; }
        public string Partner { get; set; }
        public string Competition { get; set; }
        public string NextAction { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string OpUd1 { get; set; }
        public string OpUd2 { get; set; }
        public string OpUd3 { get; set; }
        public string OpUd4 { get; set; }
        public string OpUd5 { get; set; }
        public string OpUd6 { get; set; }
        public string OpUd7 { get; set; }
        public string OpUd8 { get; set; }
        public string OpUd9 { get; set; }
        public string OpUd10 { get; set; }
        public string OpUd11 { get; set; }
        public string OpUd12 { get; set; }
        public string OpUd13 { get; set; }
        public string OpUd14 { get; set; }
        public string OpUd15 { get; set; }
        public Guid? OpUd1Id { get; set; }
        public Guid? OpUd2Id { get; set; }
        public Guid? OpUd3Id { get; set; }
        public Guid? OpUd4Id { get; set; }
        public Guid? OpUd5Id { get; set; }
        public Guid? OpUd6Id { get; set; }
        public Guid? OpUd7Id { get; set; }
        public Guid? OpUd8Id { get; set; }
        public Guid? OpUd9Id { get; set; }
        public Guid? OpUd10Id { get; set; }
        public DateTime? OpUd1Date { get; set; }
        public DateTime? OpUd2Date { get; set; }
        public DateTime? OpUd3Date { get; set; }
        public DateTime? OpUd4Date { get; set; }
        public DateTime? OpUd5Date { get; set; }
        public DateTime? OpUd6Date { get; set; }
        public DateTime? OpUd7Date { get; set; }
        public DateTime? OpUd8Date { get; set; }
        public DateTime? OpUd9Date { get; set; }
        public DateTime? OpUd10Date { get; set; }
        public bool? OpUd1Bit { get; set; }
        public bool? OpUd2Bit { get; set; }
        public bool? OpUd3Bit { get; set; }
        public bool? OpUd4Bit { get; set; }
        public bool? OpUd5Bit { get; set; }
        public bool? OpUd6Bit { get; set; }
        public bool? OpUd7Bit { get; set; }
        public bool? OpUd8Bit { get; set; }
        public bool? OpUd9Bit { get; set; }
        public bool? OpUd10Bit { get; set; }
        public decimal? OpUd1Numeric { get; set; }
        public decimal? OpUd2Numeric { get; set; }
        public decimal? OpUd3Numeric { get; set; }
        public decimal? OpUd4Numeric { get; set; }
        public decimal? OpUd5Numeric { get; set; }
        public decimal? OpUd6Numeric { get; set; }
        public decimal? OpUd7Numeric { get; set; }
        public decimal? OpUd8Numeric { get; set; }
        public decimal? OpUd9Numeric { get; set; }
        public decimal? OpUd10Numeric { get; set; }
        public string OpExternal { get; set; }
        public decimal? Margin { get; set; }
        public decimal? MarginPercentage { get; set; }
        public bool? Closed { get; set; }
        public string Reference { get; set; }
        public bool? OpUd11Bit { get; set; }
        public bool? OpUd12Bit { get; set; }
        public bool? OpUd13Bit { get; set; }
        public bool? OpUd14Bit { get; set; }
        public bool? OpUd15Bit { get; set; }
        public bool? OpUd16Bit { get; set; }
        public bool? OpUd17Bit { get; set; }
        public bool? OpUd18Bit { get; set; }
        public bool? OpUd19Bit { get; set; }
        public bool? OpUd20Bit { get; set; }
        public bool? OpUd21Bit { get; set; }
        public bool? OpUd22Bit { get; set; }
        public bool? OpUd23Bit { get; set; }
        public bool? OpUd24Bit { get; set; }
        public Guid? MacIdSource { get; set; }
        public byte? OpState { get; set; }
        public Guid? CurId { get; set; }
        public Guid? OpImport { get; set; }
        public Guid? StgId { get; set; }
        public Guid? SgId { get; set; }
        public decimal? PotentialValueBase { get; set; }
        public decimal? ForecastValueBase { get; set; }
        public Guid? OpIdEdit { get; set; }
        public int Overdue { get; set; }
        public int? DaysOpen { get; set; }
        public DateTime? ForecastDate { get; set; }
        public string OpUd1IdName { get; set; }
        public string OpUd2IdName { get; set; }
        public string OpUd3IdName { get; set; }
        public string OpUd4IdName { get; set; }
        public string OpUd5IdName { get; set; }
        public string OpUd6IdName { get; set; }
        public string OpUd7IdName { get; set; }
        public string OpUd8IdName { get; set; }
        public string OpUd9IdName { get; set; }
        public string OpUd10IdName { get; set; }
        public string OpUd1IdNameHlight { get; set; }
        public string OpUd2IdNameHlight { get; set; }
        public string OpUd3IdNameHlight { get; set; }
        public string OpUd4IdNameHlight { get; set; }
        public string OpUd5IdNameHlight { get; set; }
        public string OpUd6IdNameHlight { get; set; }
        public string OpUd7IdNameHlight { get; set; }
        public string OpUd8IdNameHlight { get; set; }
        public string OpUd9IdNameHlight { get; set; }
        public string OpUd10IdNameHlight { get; set; }
        public string OpContactName { get; set; }
        public int? OpDuration { get; set; }
        public string OpSource { get; set; }
        public string ProductType { get; set; }
        public string OpStage { get; set; }
        public string OpSourceHlight { get; set; }
        public string ProductTypeHlight { get; set; }
        public string OpStageHlight { get; set; }
        public string OwnerName { get; set; }
        public string OwnerDept { get; set; }
        public string OwnerEmail { get; set; }
        public Guid? UsgId { get; set; }
        public string OwnerGroup { get; set; }
        public string OpContactEmail { get; set; }
        public string OpContactPhone { get; set; }
        public string AccName { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public string MacIdSourceName { get; set; }
        public string StgIdName { get; set; }
        public Guid? McaId { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
        public string AcName { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string AcType1 { get; set; }
        public string AcType2 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2Hlight { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AccountManager { get; set; }
        public string AccountManagerEmail { get; set; }
        public string AcPhone1 { get; set; }
        public string AcAddress1 { get; set; }
        public string AcAddress2 { get; set; }
        public string AcAddress3 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcCountry { get; set; }
        public string AcBillingAddress1 { get; set; }
        public string AcBillingAddress2 { get; set; }
        public string AcBillingAddress3 { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcReference { get; set; }
        public string AcExternal { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public string AcUd1Id { get; set; }
        public string AcUd2Id { get; set; }
        public string AcUd3Id { get; set; }
        public string AcUd4Id { get; set; }
        public string AcUd5Id { get; set; }
        public string AcUd6Id { get; set; }
        public string AcUd7Id { get; set; }
        public string AcUd8Id { get; set; }
        public string AcUd9Id { get; set; }
        public string AcUd10Id { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string ClosedMore { get; set; }
        public string ImSummary { get; set; }
        public Guid SecurityId { get; set; }
        public string SecurityGroup { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public int EstimatedUnits { get; set; }
        public int EstimatedTime { get; set; }
        public int ActualUnits { get; set; }
        public int ActualTime { get; set; }
        public string ShortCode { get; set; }
        public Guid? SitId { get; set; }
        public string SiteName { get; set; }
    }
}
