using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VOpportunitiesQuotesDetail
    {
        public Guid? AcId { get; set; }
        public Guid? OpId { get; set; }
        public Guid? OpqId { get; set; }
        public Guid? PrId { get; set; }
        public Guid OpqdId { get; set; }
        public bool? OpqdDeleted { get; set; }
        public string Code { get; set; }
        public string ProductGroup { get; set; }
        public string Manufacturer { get; set; }
        public double? Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal PriceHidden { get; set; }
        public double? Discount { get; set; }
        public decimal? Vat { get; set; }
        public decimal PriceDiscount { get; set; }
        public decimal PriceFinal { get; set; }
        public string Summary { get; set; }
        public string ShortCode { get; set; }
        public string Details { get; set; }
        public decimal? ListPriceTotal { get; set; }
        public decimal? SubTotal { get; set; }
        public decimal? Tax { get; set; }
        public decimal? AccountDiscount { get; set; }
        public decimal? GrandTotal { get; set; }
        public string ProductName { get; set; }
        public decimal? DiscountPrice { get; set; }
        public decimal? NetPrice { get; set; }
        public decimal? TaxPercentage { get; set; }
        public Guid? TxcId { get; set; }
        public string TxcSummary { get; set; }
        public string Info { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string SortOrder { get; set; }
        public bool? Excludefromtotal { get; set; }
        public double? RateWhenAdded { get; set; }
        public decimal? Cost { get; set; }
        public string Ud1 { get; set; }
        public string Ud2 { get; set; }
        public string Ud3 { get; set; }
        public string Ud4 { get; set; }
        public string Ud5 { get; set; }
        public string Ud6 { get; set; }
        public string Ud7 { get; set; }
        public string Ud8 { get; set; }
        public string Ud9 { get; set; }
        public string Ud10 { get; set; }
        public string Ud11 { get; set; }
        public string Ud12 { get; set; }
        public string Ud13 { get; set; }
        public string Ud14 { get; set; }
        public string Ud15 { get; set; }
        public string PrUd1 { get; set; }
        public string PrUd2 { get; set; }
        public string PrUd3 { get; set; }
        public string PrUd4 { get; set; }
        public string PrUd5 { get; set; }
        public string PrUd6 { get; set; }
        public string PrUd7 { get; set; }
        public string PrUd8 { get; set; }
        public string PrUd9 { get; set; }
        public string PrUd10 { get; set; }
        public string PrUd11 { get; set; }
        public string PrUd12 { get; set; }
        public string PrUd13 { get; set; }
        public string PrUd14 { get; set; }
        public string PrUd15 { get; set; }
        public DateTime? PrUd1Date { get; set; }
        public DateTime? PrUd2Date { get; set; }
        public DateTime? PrUd3Date { get; set; }
        public DateTime? PrUd4Date { get; set; }
        public DateTime? PrUd5Date { get; set; }
        public DateTime? PrUd6Date { get; set; }
        public DateTime? PrUd7Date { get; set; }
        public DateTime? PrUd8Date { get; set; }
        public DateTime? PrUd9Date { get; set; }
        public DateTime? PrUd10Date { get; set; }
        public bool? PrUd1Bit { get; set; }
        public bool? PrUd2Bit { get; set; }
        public bool? PrUd3Bit { get; set; }
        public bool? PrUd4Bit { get; set; }
        public bool? PrUd5Bit { get; set; }
        public bool? PrUd6Bit { get; set; }
        public bool? PrUd7Bit { get; set; }
        public bool? PrUd8Bit { get; set; }
        public bool? PrUd9Bit { get; set; }
        public bool? PrUd10Bit { get; set; }
        public decimal? PrUd1Numeric { get; set; }
        public decimal? PrUd2Numeric { get; set; }
        public decimal? PrUd3Numeric { get; set; }
        public decimal? PrUd4Numeric { get; set; }
        public decimal? PrUd5Numeric { get; set; }
        public decimal? PrUd6Numeric { get; set; }
        public decimal? PrUd7Numeric { get; set; }
        public decimal? PrUd8Numeric { get; set; }
        public decimal? PrUd9Numeric { get; set; }
        public decimal? PrUd10Numeric { get; set; }
        public decimal? PrUd11Numeric { get; set; }
        public decimal? PrUd12Numeric { get; set; }
        public decimal? PrUd13Numeric { get; set; }
        public decimal? PrUd14Numeric { get; set; }
        public decimal? PrUd15Numeric { get; set; }
        public string PrUd1IdName { get; set; }
        public string PrUd2IdName { get; set; }
        public string PrUd3IdName { get; set; }
        public string PrUd4IdName { get; set; }
        public string PrUd5IdName { get; set; }
        public string PrUd6IdName { get; set; }
        public string PrUd7IdName { get; set; }
        public string PrUd8IdName { get; set; }
        public string PrUd9IdName { get; set; }
        public string PrUd10IdName { get; set; }
        public string PrUd1IdHlight { get; set; }
        public string PrUd2IdHlight { get; set; }
        public string PrUd3IdHlight { get; set; }
        public string PrUd4IdHlight { get; set; }
        public string PrUd5IdHlight { get; set; }
        public string PrUd6IdHlight { get; set; }
        public string PrUd7IdHlight { get; set; }
        public string PrUd8IdHlight { get; set; }
        public string PrUd9IdHlight { get; set; }
        public string PrUd10IdHlight { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Guid? PrUd1Id { get; set; }
        public Guid? PrUd2Id { get; set; }
        public Guid? PrUd3Id { get; set; }
        public Guid? PrUd4Id { get; set; }
        public Guid? PrUd5Id { get; set; }
        public Guid? PrUd6Id { get; set; }
        public Guid? PrUd7Id { get; set; }
        public Guid? PrUd8Id { get; set; }
        public Guid? PrUd9Id { get; set; }
        public Guid? PrUd10Id { get; set; }
        public byte? OpqState { get; set; }
        public string OpqSummary { get; set; }
        public string PrSummary { get; set; }
        public string OpqName { get; set; }
        public string PrName { get; set; }
        public Guid? PrgId { get; set; }
        public string PrgSummary { get; set; }
        public string PrUd1IdNameHlight { get; set; }
        public string PrUd2IdNameHlight { get; set; }
        public string PrUd3IdNameHlight { get; set; }
        public string PrUd4IdNameHlight { get; set; }
        public string PrUd5IdNameHlight { get; set; }
        public string PrUd6IdNameHlight { get; set; }
        public string PrUd7IdNameHlight { get; set; }
        public string PrUd8IdNameHlight { get; set; }
        public string PrUd9IdNameHlight { get; set; }
        public string PrUd10IdNameHlight { get; set; }
        public string Reference { get; set; }
        public int TimeUnitValue { get; set; }
        public bool TimeUnitIsTime { get; set; }
        public int TimeUnitValueTotal { get; set; }
        public int? RemainingTimeUnits { get; set; }
        public int SpentTimeUnits { get; set; }
        public int Linked { get; set; }
        public string TxcExternal { get; set; }
        public string PrExternal { get; set; }
    }
}
