using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VOpportunitiesQuote
    {
        public Guid? AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid? OpId { get; set; }
        public Guid OpqId { get; set; }
        public bool? OpqDeleted { get; set; }
        public Guid? OpqType { get; set; }
        public string OpqNumber { get; set; }
        public string Reference { get; set; }
        public string Template { get; set; }
        public string Summary { get; set; }
        public decimal? Value { get; set; }
        public string SentStatus { get; set; }
        public DateTime? Expires { get; set; }
        public DateTime? EstimatedClose { get; set; }
        public DateTime? ActualClose { get; set; }
        public DateTime? ForecastDate { get; set; }
        public double NumberOfItems { get; set; }
        public decimal CostItems { get; set; }
        public double DiscountItems { get; set; }
        public decimal CostQuote { get; set; }
        public double? CostQuoteBase { get; set; }
        public double DiscountAccount { get; set; }
        public decimal CostSub { get; set; }
        public decimal CostCarriage { get; set; }
        public decimal CostMisc { get; set; }
        public decimal CostUpdatedSub { get; set; }
        public decimal CostVat { get; set; }
        public decimal CostTotal { get; set; }
        public bool? AddToOpportunity { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string OpqUd1 { get; set; }
        public string OpqUd2 { get; set; }
        public string OpqUd3 { get; set; }
        public string OpqUd4 { get; set; }
        public string OpqUd5 { get; set; }
        public string OpqUd6 { get; set; }
        public string OpqUd7 { get; set; }
        public string OpqUd8 { get; set; }
        public string OpqUd9 { get; set; }
        public string OpqUd10 { get; set; }
        public string OpqUd11 { get; set; }
        public string OpqUd12 { get; set; }
        public string OpqUd13 { get; set; }
        public string OpqUd14 { get; set; }
        public string OpqUd15 { get; set; }
        public Guid? CurId { get; set; }
        public Guid? CurIdPriceList { get; set; }
        public decimal? Margin { get; set; }
        public decimal? MarginPercentage { get; set; }
        public Guid? Owner { get; set; }
        public Guid? OpqUd1Id { get; set; }
        public Guid? OpqUd2Id { get; set; }
        public Guid? OpqUd3Id { get; set; }
        public Guid? OpqUd4Id { get; set; }
        public Guid? OpqUd5Id { get; set; }
        public Guid? OpqUd6Id { get; set; }
        public Guid? OpqUd7Id { get; set; }
        public Guid? OpqUd8Id { get; set; }
        public Guid? OpqUd9Id { get; set; }
        public Guid? OpqUd10Id { get; set; }
        public DateTime? OpqUd1Date { get; set; }
        public DateTime? OpqUd2Date { get; set; }
        public DateTime? OpqUd3Date { get; set; }
        public DateTime? OpqUd4Date { get; set; }
        public DateTime? OpqUd5Date { get; set; }
        public DateTime? OpqUd6Date { get; set; }
        public DateTime? OpqUd7Date { get; set; }
        public DateTime? OpqUd8Date { get; set; }
        public DateTime? OpqUd9Date { get; set; }
        public DateTime? OpqUd10Date { get; set; }
        public decimal? OpqUd1Numeric { get; set; }
        public decimal? OpqUd2Numeric { get; set; }
        public decimal? OpqUd3Numeric { get; set; }
        public decimal? OpqUd4Numeric { get; set; }
        public decimal? OpqUd5Numeric { get; set; }
        public decimal? OpqUd6Numeric { get; set; }
        public decimal? OpqUd7Numeric { get; set; }
        public decimal? OpqUd8Numeric { get; set; }
        public decimal? OpqUd9Numeric { get; set; }
        public decimal? OpqUd10Numeric { get; set; }
        public bool? OpqUd1Bit { get; set; }
        public bool? OpqUd2Bit { get; set; }
        public bool? OpqUd3Bit { get; set; }
        public bool? OpqUd4Bit { get; set; }
        public bool? OpqUd5Bit { get; set; }
        public bool? OpqUd6Bit { get; set; }
        public bool? OpqUd7Bit { get; set; }
        public bool? OpqUd8Bit { get; set; }
        public bool? OpqUd9Bit { get; set; }
        public bool? OpqUd10Bit { get; set; }
        public bool? OpqUd11Bit { get; set; }
        public bool? OpqUd12Bit { get; set; }
        public bool? OpqUd13Bit { get; set; }
        public bool? OpqUd14Bit { get; set; }
        public bool? OpqUd15Bit { get; set; }
        public bool? OpqUd16Bit { get; set; }
        public bool? OpqUd17Bit { get; set; }
        public bool? OpqUd18Bit { get; set; }
        public bool? OpqUd19Bit { get; set; }
        public bool? OpqUd20Bit { get; set; }
        public bool? OpqUd21Bit { get; set; }
        public bool? OpqUd22Bit { get; set; }
        public bool? OpqUd23Bit { get; set; }
        public bool? OpqUd24Bit { get; set; }
        public bool? ForcedClose { get; set; }
        public byte? OpqState { get; set; }
        public Guid? OpqIdEdit { get; set; }
        public string Company { get; set; }
        public string QuoteContact { get; set; }
        public string QuoteContactPhone { get; set; }
        public string QuoteContactEmail { get; set; }
        public string QuoteContactFax { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public string Type { get; set; }
        public string TypeHlight { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BusinessFaxNumberFormatted { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
        public double CurrencyRate { get; set; }
        public int? DaysOpen { get; set; }
        public string State { get; set; }
        public string AcName { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AcPhone1 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcReference { get; set; }
        public string AcBillingAddress1 { get; set; }
        public string AcBillingAddress2 { get; set; }
        public string AcBillingAddress3 { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcExternal { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerDept { get; set; }
        public string OwnerGroup { get; set; }
        public Guid? UsgId { get; set; }
        public string AcManager { get; set; }
        public string AcManagerEmail { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcType1 { get; set; }
        public string AcType2 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2Hlight { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public string AcUd1Id { get; set; }
        public string AcUd2Id { get; set; }
        public string AcUd3Id { get; set; }
        public string AcUd4Id { get; set; }
        public string AcUd5Id { get; set; }
        public string AcUd6Id { get; set; }
        public string AcUd7Id { get; set; }
        public string AcUd8Id { get; set; }
        public string AcUd9Id { get; set; }
        public string AcUd10Id { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string OpName { get; set; }
        public Guid? OpOwner { get; set; }
        public byte? OpState { get; set; }
        public string OpStage { get; set; }
        public string OpType { get; set; }
        public string OpSource { get; set; }
        public string OpStageHlight { get; set; }
        public string OpTypeHlight { get; set; }
        public string OpSourceHlight { get; set; }
        public decimal? OpValue { get; set; }
        public decimal? OpForecast { get; set; }
        public DateTime? OpEstimatedClose { get; set; }
        public DateTime? OpActualClose { get; set; }
        public bool? OpAddToForecast { get; set; }
        public decimal? OpProbability { get; set; }
        public string OpReference { get; set; }
        public string Currency { get; set; }
        public double? Exchange { get; set; }
        public string Code { get; set; }
        public string PriceListCurrency { get; set; }
        public double? PriceListExchange { get; set; }
        public string PriceListCode { get; set; }
        public string CurExternal { get; set; }
        public string OpqUd1IdName { get; set; }
        public string OpqUd2IdName { get; set; }
        public string OpqUd3IdName { get; set; }
        public string OpqUd4IdName { get; set; }
        public string OpqUd5IdName { get; set; }
        public string OpqUd6IdName { get; set; }
        public string OpqUd7IdName { get; set; }
        public string OpqUd8IdName { get; set; }
        public string OpqUd9IdName { get; set; }
        public string OpqUd10IdName { get; set; }
        public string OpqUd1IdNameHlight { get; set; }
        public string OpqUd2IdNameHlight { get; set; }
        public string OpqUd3IdNameHlight { get; set; }
        public string OpqUd4IdNameHlight { get; set; }
        public string OpqUd5IdNameHlight { get; set; }
        public string OpqUd6IdNameHlight { get; set; }
        public string OpqUd7IdNameHlight { get; set; }
        public string OpqUd8IdNameHlight { get; set; }
        public string OpqUd9IdNameHlight { get; set; }
        public string OpqUd10IdNameHlight { get; set; }
        public string ContactAccountname { get; set; }
        public Guid? ContactAcid { get; set; }
        public DateTime? OpqEstimatedClose { get; set; }
        public DateTime? OpqActualClose { get; set; }
        public Guid? FneId { get; set; }
        public string FneName { get; set; }
        public Guid? SecurityId { get; set; }
        public string SecurityGroup { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public decimal? ExchangeRate { get; set; }
        public Guid? SitId { get; set; }
        public string SiteName { get; set; }
        public string SiteTypeName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string SitExternal { get; set; }
        public string SiteTypeNameHlight { get; set; }
        public bool? Scheduled { get; set; }
        public string Details { get; set; }
        public int TimeTotal { get; set; }
        public int UnitsTotal { get; set; }
        public string ShortCode { get; set; }
    }
}
