using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VProductSalesAll
    {
        public Guid? OpId { get; set; }
        public Guid? OpqId { get; set; }
        public Guid? PrId { get; set; }
        public Guid? SembId { get; set; }
        public Guid? SemId { get; set; }
        public Guid OpqdId { get; set; }
        public Guid? OpqdOrPrId { get; set; }
        public string ProductItemType { get; set; }
        public bool? OpqdDeleted { get; set; }
        public string Code { get; set; }
        public string ProductGroup { get; set; }
        public string Manufacturer { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public double Discount { get; set; }
        public decimal PriceDiscount { get; set; }
        public decimal PriceFinal { get; set; }
        public double? PriceFinalBase { get; set; }
        public double? PriceFinalLocal { get; set; }
        public string Summary { get; set; }
        public decimal? TaxPercentage { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public bool? Excludefromtotal { get; set; }
        public decimal? Cost { get; set; }
        public double? Margin { get; set; }
        public decimal? MarginPercent { get; set; }
        public double? DiscountedPrice { get; set; }
        public DateTime? CloseDate { get; set; }
        public DateTime? ForecastDate { get; set; }
        public DateTime? EstimatedClose { get; set; }
        public Guid? AccId { get; set; }
        public string AccSummary { get; set; }
        public Guid AcId { get; set; }
        public string AcName { get; set; }
        public string OpSummary { get; set; }
        public string SembName { get; set; }
        public string SemName { get; set; }
        public string ParentSummary { get; set; }
        public Guid ParentId { get; set; }
        public string ParentType { get; set; }
        public string ParentTypeLabel { get; set; }
        public Guid? Owner { get; set; }
        public string OwnerName { get; set; }
        public string ProductName { get; set; }
        public string QuoteSummary { get; set; }
        public string OpqNumber { get; set; }
        public Guid? PrIdFk { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
        public string AcGroup { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string State { get; set; }
        public string PrUd1 { get; set; }
        public string PrUd2 { get; set; }
        public string PrUd3 { get; set; }
        public string PrUd4 { get; set; }
        public string PrUd5 { get; set; }
        public string PrUd6 { get; set; }
        public string PrUd7 { get; set; }
        public string PrUd8 { get; set; }
        public string PrUd9 { get; set; }
        public string PrUd10 { get; set; }
        public string PrUd11 { get; set; }
        public string PrUd12 { get; set; }
        public string PrUd13 { get; set; }
        public string PrUd14 { get; set; }
        public string PrUd15 { get; set; }
        public bool? PrUd1Bit { get; set; }
        public bool? PrUd2Bit { get; set; }
        public bool? PrUd3Bit { get; set; }
        public bool? PrUd4Bit { get; set; }
        public bool? PrUd5Bit { get; set; }
        public bool? PrUd6Bit { get; set; }
        public bool? PrUd7Bit { get; set; }
        public bool? PrUd8Bit { get; set; }
        public bool? PrUd9Bit { get; set; }
        public bool? PrUd10Bit { get; set; }
        public bool? PrUd11Bit { get; set; }
        public bool? PrUd12Bit { get; set; }
        public bool? PrUd13Bit { get; set; }
        public bool? PrUd14Bit { get; set; }
        public bool? PrUd15Bit { get; set; }
        public bool? PrUd16Bit { get; set; }
        public bool? PrUd17Bit { get; set; }
        public bool? PrUd18Bit { get; set; }
        public bool? PrUd19Bit { get; set; }
        public bool? PrUd20Bit { get; set; }
        public bool? PrUd21Bit { get; set; }
        public bool? PrUd22Bit { get; set; }
        public bool? PrUd23Bit { get; set; }
        public bool? PrUd24Bit { get; set; }
        public DateTime? PrUd1Date { get; set; }
        public DateTime? PrUd2Date { get; set; }
        public DateTime? PrUd3Date { get; set; }
        public DateTime? PrUd4Date { get; set; }
        public DateTime? PrUd5Date { get; set; }
        public DateTime? PrUd6Date { get; set; }
        public DateTime? PrUd7Date { get; set; }
        public DateTime? PrUd8Date { get; set; }
        public DateTime? PrUd9Date { get; set; }
        public DateTime? PrUd10Date { get; set; }
        public decimal? PrUd1Numeric { get; set; }
        public decimal? PrUd2Numeric { get; set; }
        public decimal? PrUd3Numeric { get; set; }
        public decimal? PrUd4Numeric { get; set; }
        public decimal? PrUd5Numeric { get; set; }
        public decimal? PrUd6Numeric { get; set; }
        public decimal? PrUd7Numeric { get; set; }
        public decimal? PrUd8Numeric { get; set; }
        public decimal? PrUd9Numeric { get; set; }
        public decimal? PrUd10Numeric { get; set; }
        public string PrUd1IdName { get; set; }
        public string PrUd2IdName { get; set; }
        public string PrUd3IdName { get; set; }
        public string PrUd4IdName { get; set; }
        public string PrUd5IdName { get; set; }
        public string PrUd6IdName { get; set; }
        public string PrUd7IdName { get; set; }
        public string PrUd8IdName { get; set; }
        public string PrUd9IdName { get; set; }
        public string PrUd10IdName { get; set; }
        public string ProductType { get; set; }
        public string PrUd1IdNameHlight { get; set; }
        public string PrUd2IdNameHlight { get; set; }
        public string PrUd3IdNameHlight { get; set; }
        public string PrUd4IdNameHlight { get; set; }
        public string PrUd5IdNameHlight { get; set; }
        public string PrUd6IdNameHlight { get; set; }
        public string PrUd7IdNameHlight { get; set; }
        public string PrUd8IdNameHlight { get; set; }
        public string PrUd9IdNameHlight { get; set; }
        public string PrUd10IdNameHlight { get; set; }
        public string ProductTypeHlight { get; set; }
        public string OpqUd1 { get; set; }
        public string OpqUd2 { get; set; }
        public string OpqUd3 { get; set; }
        public string OpqUd4 { get; set; }
        public string OpqUd5 { get; set; }
        public string OpqUd6 { get; set; }
        public string OpqUd7 { get; set; }
        public string OpqUd8 { get; set; }
        public string OpqUd9 { get; set; }
        public string OpqUd10 { get; set; }
        public string OpqUd11 { get; set; }
        public string OpqUd12 { get; set; }
        public string OpqUd13 { get; set; }
        public string OpqUd14 { get; set; }
        public string OpqUd15 { get; set; }
        public DateTime? OpqUd1Date { get; set; }
        public DateTime? OpqUd2Date { get; set; }
        public DateTime? OpqUd3Date { get; set; }
        public DateTime? OpqUd4Date { get; set; }
        public DateTime? OpqUd5Date { get; set; }
        public DateTime? OpqUd6Date { get; set; }
        public DateTime? OpqUd7Date { get; set; }
        public DateTime? OpqUd8Date { get; set; }
        public DateTime? OpqUd9Date { get; set; }
        public DateTime? OpqUd10Date { get; set; }
        public decimal? OpqUd1Numeric { get; set; }
        public decimal? OpqUd2Numeric { get; set; }
        public decimal? OpqUd3Numeric { get; set; }
        public decimal? OpqUd4Numeric { get; set; }
        public decimal? OpqUd5Numeric { get; set; }
        public decimal? OpqUd6Numeric { get; set; }
        public decimal? OpqUd7Numeric { get; set; }
        public decimal? OpqUd8Numeric { get; set; }
        public decimal? OpqUd9Numeric { get; set; }
        public decimal? OpqUd10Numeric { get; set; }
        public bool? OpqUd1Bit { get; set; }
        public bool? OpqUd2Bit { get; set; }
        public bool? OpqUd3Bit { get; set; }
        public bool? OpqUd4Bit { get; set; }
        public bool? OpqUd5Bit { get; set; }
        public bool? OpqUd6Bit { get; set; }
        public bool? OpqUd7Bit { get; set; }
        public bool? OpqUd8Bit { get; set; }
        public bool? OpqUd9Bit { get; set; }
        public bool? OpqUd10Bit { get; set; }
        public string OpqUd1Id { get; set; }
        public string OpqUd2Id { get; set; }
        public string OpqUd3Id { get; set; }
        public string OpqUd4Id { get; set; }
        public string OpqUd5Id { get; set; }
        public string OpqUd6Id { get; set; }
        public string OpqUd7Id { get; set; }
        public string OpqUd8Id { get; set; }
        public string OpqUd9Id { get; set; }
        public string OpqUd10Id { get; set; }
        public string OpqUd1IdHlight { get; set; }
        public string OpqUd2IdHlight { get; set; }
        public string OpqUd3IdHlight { get; set; }
        public string OpqUd4IdHlight { get; set; }
        public string OpqUd5IdHlight { get; set; }
        public string OpqUd6IdHlight { get; set; }
        public string OpqUd7IdHlight { get; set; }
        public string OpqUd8IdHlight { get; set; }
        public string OpqUd9IdHlight { get; set; }
        public string OpqUd10IdHlight { get; set; }
        public string ProductDescription { get; set; }
        public string AcType1 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2 { get; set; }
        public string AcType2Hlight { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string OpStage { get; set; }
        public decimal? OpProbability { get; set; }
        public string SemStage { get; set; }
        public double? RateWhenAdded { get; set; }
        public string AccountManager { get; set; }
        public string SupportManager { get; set; }
        public string QuoteType { get; set; }
        public string FneName { get; set; }
        public string PfneName { get; set; }
        public Guid? SecurityId { get; set; }
        public string Security { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public string OpSource { get; set; }
        public string OpSourceHlight { get; set; }
        public string QuoteItemDescription { get; set; }
        public string OpportunitySourceCampaign { get; set; }
        public string AccEmail1address { get; set; }
        public bool? OpqUd11Bit { get; set; }
        public bool? OpqUd12Bit { get; set; }
        public bool? OpqUd13Bit { get; set; }
        public bool? OpqUd14Bit { get; set; }
        public bool? OpqUd15Bit { get; set; }
        public bool? OpqUd16Bit { get; set; }
        public bool? OpqUd17Bit { get; set; }
        public bool? OpqUd18Bit { get; set; }
        public bool? OpqUd19Bit { get; set; }
        public bool? OpqUd20Bit { get; set; }
        public bool? OpqUd21Bit { get; set; }
        public bool? OpqUd22Bit { get; set; }
        public bool? OpqUd23Bit { get; set; }
        public bool? OpqUd24Bit { get; set; }
        public int? TimeUnitValue { get; set; }
        public bool? TimeUnitIsTime { get; set; }
        public int? TimeUnitValueTotal { get; set; }
        public int? SpentTimeUnits { get; set; }
        public int? RemainingTimeUnits { get; set; }
        public int? Linked { get; set; }
    }
}
