using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VProject
    {
        public Guid? AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid? Owner { get; set; }
        public Guid PjId { get; set; }
        public bool PjDeleted { get; set; }
        public Guid? PjFlag { get; set; }
        public decimal? Value { get; set; }
        public Guid? Stage { get; set; }
        public Guid? NextAction { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? CompletionDate { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public Guid? SitId { get; set; }
        public string SiteName { get; set; }
        public string PjUd1Text { get; set; }
        public string PjUd2Text { get; set; }
        public string PjUd3Text { get; set; }
        public string PjUd4Text { get; set; }
        public string PjUd5Text { get; set; }
        public string PjUd6Text { get; set; }
        public string PjUd7Text { get; set; }
        public string PjUd8Text { get; set; }
        public string PjUd9Text { get; set; }
        public string PjUd10Text { get; set; }
        public DateTime? PjUd1Date { get; set; }
        public DateTime? PjUd2Date { get; set; }
        public DateTime? PjUd3Date { get; set; }
        public DateTime? PjUd4Date { get; set; }
        public DateTime? PjUd5Date { get; set; }
        public DateTime? PjUd6Date { get; set; }
        public DateTime? PjUd7Date { get; set; }
        public DateTime? PjUd8Date { get; set; }
        public DateTime? PjUd9Date { get; set; }
        public DateTime? PjUd10Date { get; set; }
        public Guid? PjUd1Id { get; set; }
        public Guid? PjUd2Id { get; set; }
        public Guid? PjUd3Id { get; set; }
        public Guid? PjUd4Id { get; set; }
        public Guid? PjUd5Id { get; set; }
        public Guid? PjUd6Id { get; set; }
        public Guid? PjUd7Id { get; set; }
        public Guid? PjUd8Id { get; set; }
        public Guid? PjUd9Id { get; set; }
        public Guid? PjUd10Id { get; set; }
        public bool? PjUd1Bit { get; set; }
        public bool? PjUd2Bit { get; set; }
        public bool? PjUd3Bit { get; set; }
        public bool? PjUd4Bit { get; set; }
        public bool? PjUd5Bit { get; set; }
        public bool? PjUd6Bit { get; set; }
        public bool? PjUd7Bit { get; set; }
        public bool? PjUd8Bit { get; set; }
        public bool? PjUd9Bit { get; set; }
        public bool? PjUd10Bit { get; set; }
        public Guid? OpId { get; set; }
        public decimal? PjUd1Numeric { get; set; }
        public decimal? PjUd2Numeric { get; set; }
        public decimal? PjUd3Numeric { get; set; }
        public decimal? PjUd4Numeric { get; set; }
        public decimal? PjUd5Numeric { get; set; }
        public decimal? PjUd6Numeric { get; set; }
        public decimal? PjUd7Numeric { get; set; }
        public decimal? PjUd8Numeric { get; set; }
        public decimal? PjUd9Numeric { get; set; }
        public decimal? PjUd10Numeric { get; set; }
        public string PjExternal { get; set; }
        public Guid? PjImport { get; set; }
        public string Reference { get; set; }
        public bool? PjUd11Bit { get; set; }
        public bool? PjUd12Bit { get; set; }
        public bool? PjUd13Bit { get; set; }
        public bool? PjUd14Bit { get; set; }
        public bool? PjUd15Bit { get; set; }
        public bool? PjUd16Bit { get; set; }
        public bool? PjUd17Bit { get; set; }
        public bool? PjUd18Bit { get; set; }
        public bool? PjUd19Bit { get; set; }
        public bool? PjUd20Bit { get; set; }
        public bool? PjUd21Bit { get; set; }
        public bool? PjUd22Bit { get; set; }
        public bool? PjUd23Bit { get; set; }
        public bool? PjUd24Bit { get; set; }
        public Guid? SgId { get; set; }
        public int? DaysOpen { get; set; }
        public string ImSummary { get; set; }
        public string UsName { get; set; }
        public string UsEmail { get; set; }
        public string UsDept { get; set; }
        public string UsgName { get; set; }
        public Guid? UsgId { get; set; }
        public string PjFlagName { get; set; }
        public string PjStage { get; set; }
        public string PjState { get; set; }
        public string PjNextAction { get; set; }
        public string PjUd1IdName { get; set; }
        public string PjUd2IdName { get; set; }
        public string PjUd3IdName { get; set; }
        public string PjUd4IdName { get; set; }
        public string PjUd5IdName { get; set; }
        public string PjUd6IdName { get; set; }
        public string PjUd7IdName { get; set; }
        public string PjUd8IdName { get; set; }
        public string PjUd9IdName { get; set; }
        public string PjUd10IdName { get; set; }
        public string PjFlagNameHlight { get; set; }
        public string PjStageHlight { get; set; }
        public string PjNextActionHlight { get; set; }
        public string PjUd1IdNameHlight { get; set; }
        public string PjUd2IdNameHlight { get; set; }
        public string PjUd3IdNameHlight { get; set; }
        public string PjUd4IdNameHlight { get; set; }
        public string PjUd5IdNameHlight { get; set; }
        public string PjUd6IdNameHlight { get; set; }
        public string PjUd7IdNameHlight { get; set; }
        public string PjUd8IdNameHlight { get; set; }
        public string PjUd9IdNameHlight { get; set; }
        public string PjUd10IdNameHlight { get; set; }
        public string AcName { get; set; }
        public Guid? AcManId { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string AcType1 { get; set; }
        public string AcType2 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2Hlight { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AcMan { get; set; }
        public string AcManEmail { get; set; }
        public string AcPhone1 { get; set; }
        public string AcAddress1 { get; set; }
        public string AcAddress2 { get; set; }
        public string AcAddress3 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcCountry { get; set; }
        public string AcBillingAddress1 { get; set; }
        public string AcBillingAddress2 { get; set; }
        public string AcBillingAddress3 { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcReference { get; set; }
        public string AcExternal { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public Guid? AcUd1Id { get; set; }
        public Guid? AcUd10Id { get; set; }
        public Guid? AcUd2Id { get; set; }
        public Guid? AcUd3Id { get; set; }
        public Guid? AcUd4Id { get; set; }
        public Guid? AcUd5Id { get; set; }
        public Guid? AcUd6Id { get; set; }
        public Guid? AcUd7Id { get; set; }
        public Guid? AcUd8Id { get; set; }
        public Guid? AcUd9Id { get; set; }
        public string AccName { get; set; }
        public string AccEmail { get; set; }
        public string AccPhone { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public Guid SecurityId { get; set; }
        public string SecurityGroup { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public int? NextActivityId { get; set; }
        public int? NextActivity { get; set; }
        public int EstimatedUnits { get; set; }
        public int EstimatedTime { get; set; }
        public int ActualUnits { get; set; }
        public int ActualTime { get; set; }
        public string ShortCode { get; set; }
    }
}
