using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VSalesAll
    {
        public Guid? Id { get; set; }
        public string OpSemType { get; set; }
        public Guid OpqSembId { get; set; }
        public Guid? OpqSembIdOpen { get; set; }
        public string OpqSembType { get; set; }
        public string Summary { get; set; }
        public string QuoteBookingName { get; set; }
        public string Type { get; set; }
        public string TypeHlight { get; set; }
        public string Stage { get; set; }
        public string StageHlight { get; set; }
        public string Source { get; set; }
        public string SourceHlight { get; set; }
        public Guid AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid? OpId { get; set; }
        public Guid? SemId { get; set; }
        public Guid? Owner { get; set; }
        public string Reference { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public decimal Probability { get; set; }
        public int Overdue { get; set; }
        public int? DaysOpen { get; set; }
        public DateTime? ForecastDate { get; set; }
        public string State { get; set; }
        public decimal? SalesValue { get; set; }
        public double? SalesValueBase { get; set; }
        public decimal? ForecastValue { get; set; }
        public double? ForecastValueBase { get; set; }
        public decimal? Margin { get; set; }
        public double? MarginBase { get; set; }
        public DateTime? EstimatedClose { get; set; }
        public DateTime? ActualClose { get; set; }
        public double? Exchange { get; set; }
        public string Currency { get; set; }
        public string CurrencySymbol { get; set; }
        public string Code { get; set; }
        public string OpUd1 { get; set; }
        public string OpUd2 { get; set; }
        public string OpUd3 { get; set; }
        public string OpUd4 { get; set; }
        public string OpUd5 { get; set; }
        public string OpUd6 { get; set; }
        public string OpUd7 { get; set; }
        public string OpUd8 { get; set; }
        public string OpUd9 { get; set; }
        public string OpUd10 { get; set; }
        public string OpUd11 { get; set; }
        public string OpUd12 { get; set; }
        public string OpUd13 { get; set; }
        public string OpUd14 { get; set; }
        public string OpUd15 { get; set; }
        public bool? OpUd1Bit { get; set; }
        public bool? OpUd2Bit { get; set; }
        public bool? OpUd3Bit { get; set; }
        public bool? OpUd4Bit { get; set; }
        public bool? OpUd5Bit { get; set; }
        public bool? OpUd6Bit { get; set; }
        public bool? OpUd7Bit { get; set; }
        public bool? OpUd8Bit { get; set; }
        public bool? OpUd9Bit { get; set; }
        public bool? OpUd10Bit { get; set; }
        public bool? OpUd11Bit { get; set; }
        public bool? OpUd12Bit { get; set; }
        public bool? OpUd13Bit { get; set; }
        public bool? OpUd14Bit { get; set; }
        public bool? OpUd15Bit { get; set; }
        public bool? OpUd16Bit { get; set; }
        public bool? OpUd17Bit { get; set; }
        public bool? OpUd18Bit { get; set; }
        public bool? OpUd19Bit { get; set; }
        public bool? OpUd20Bit { get; set; }
        public bool? OpUd21Bit { get; set; }
        public bool? OpUd22Bit { get; set; }
        public bool? OpUd23Bit { get; set; }
        public bool? OpUd24Bit { get; set; }
        public DateTime? OpUd1Date { get; set; }
        public DateTime? OpUd2Date { get; set; }
        public DateTime? OpUd3Date { get; set; }
        public DateTime? OpUd4Date { get; set; }
        public DateTime? OpUd5Date { get; set; }
        public DateTime? OpUd6Date { get; set; }
        public DateTime? OpUd7Date { get; set; }
        public DateTime? OpUd8Date { get; set; }
        public DateTime? OpUd9Date { get; set; }
        public DateTime? OpUd10Date { get; set; }
        public Guid? OpUd1Id { get; set; }
        public Guid? OpUd2Id { get; set; }
        public Guid? OpUd3Id { get; set; }
        public Guid? OpUd4Id { get; set; }
        public Guid? OpUd5Id { get; set; }
        public Guid? OpUd6Id { get; set; }
        public Guid? OpUd7Id { get; set; }
        public Guid? OpUd8Id { get; set; }
        public Guid? OpUd9Id { get; set; }
        public Guid? OpUd10Id { get; set; }
        public decimal? OpUd1Numeric { get; set; }
        public decimal? OpUd2Numeric { get; set; }
        public decimal? OpUd3Numeric { get; set; }
        public decimal? OpUd4Numeric { get; set; }
        public decimal? OpUd5Numeric { get; set; }
        public decimal? OpUd6Numeric { get; set; }
        public decimal? OpUd7Numeric { get; set; }
        public decimal? OpUd8Numeric { get; set; }
        public decimal? OpUd9Numeric { get; set; }
        public decimal? OpUd10Numeric { get; set; }
        public Guid? OpImport { get; set; }
        public string OpExternal { get; set; }
        public string OpReference { get; set; }
        public bool? AddToForecast { get; set; }
        public string OpUd1IdName { get; set; }
        public string OpUd2IdName { get; set; }
        public string OpUd3IdName { get; set; }
        public string OpUd4IdName { get; set; }
        public string OpUd5IdName { get; set; }
        public string OpUd6IdName { get; set; }
        public string OpUd7IdName { get; set; }
        public string OpUd8IdName { get; set; }
        public string OpUd9IdName { get; set; }
        public string OpUd10IdName { get; set; }
        public string OpUd1IdNameHlight { get; set; }
        public string OpUd2IdNameHlight { get; set; }
        public string OpUd3IdNameHlight { get; set; }
        public string OpUd4IdNameHlight { get; set; }
        public string OpUd5IdNameHlight { get; set; }
        public string OpUd6IdNameHlight { get; set; }
        public string OpUd7IdNameHlight { get; set; }
        public string OpUd8IdNameHlight { get; set; }
        public string OpUd9IdNameHlight { get; set; }
        public string OpUd10IdNameHlight { get; set; }
        public Guid? OpqId { get; set; }
        public bool? OpqDeleted { get; set; }
        public Guid? OpqType { get; set; }
        public string OpqNumber { get; set; }
        public string OpqReference { get; set; }
        public string Template { get; set; }
        public string OpqSummary { get; set; }
        public string QuoteType { get; set; }
        public string QuoteTypeHlight { get; set; }
        public decimal? Value { get; set; }
        public string SentStatus { get; set; }
        public DateTime? Expires { get; set; }
        public double? NumberOfItems { get; set; }
        public decimal? CostItems { get; set; }
        public double? DiscountItems { get; set; }
        public decimal? CostQuote { get; set; }
        public double? CostQuoteBase { get; set; }
        public double? DiscountAccount { get; set; }
        public decimal? CostSub { get; set; }
        public decimal? CostCarriage { get; set; }
        public decimal? CostMisc { get; set; }
        public decimal? CostUpdatedSub { get; set; }
        public decimal? CostVat { get; set; }
        public decimal? CostTotal { get; set; }
        public bool? AddToOpportunity { get; set; }
        public string OpqUd1 { get; set; }
        public string OpqUd2 { get; set; }
        public string OpqUd3 { get; set; }
        public string OpqUd4 { get; set; }
        public string OpqUd5 { get; set; }
        public string OpqUd6 { get; set; }
        public string OpqUd7 { get; set; }
        public string OpqUd8 { get; set; }
        public string OpqUd9 { get; set; }
        public string OpqUd10 { get; set; }
        public string OpqUd11 { get; set; }
        public string OpqUd12 { get; set; }
        public string OpqUd13 { get; set; }
        public string OpqUd14 { get; set; }
        public string OpqUd15 { get; set; }
        public Guid? OpqCurId { get; set; }
        public Guid? OpqCurIdPriceList { get; set; }
        public decimal? OpqMargin { get; set; }
        public decimal? OpqMarginPercentage { get; set; }
        public Guid? OpqOwner { get; set; }
        public Guid? OpqUd1Id { get; set; }
        public Guid? OpqUd2Id { get; set; }
        public Guid? OpqUd3Id { get; set; }
        public Guid? OpqUd4Id { get; set; }
        public Guid? OpqUd5Id { get; set; }
        public Guid? OpqUd6Id { get; set; }
        public Guid? OpqUd7Id { get; set; }
        public Guid? OpqUd8Id { get; set; }
        public Guid? OpqUd9Id { get; set; }
        public Guid? OpqUd10Id { get; set; }
        public DateTime? OpqUd1Date { get; set; }
        public DateTime? OpqUd2Date { get; set; }
        public DateTime? OpqUd3Date { get; set; }
        public DateTime? OpqUd4Date { get; set; }
        public DateTime? OpqUd5Date { get; set; }
        public DateTime? OpqUd6Date { get; set; }
        public DateTime? OpqUd7Date { get; set; }
        public DateTime? OpqUd8Date { get; set; }
        public DateTime? OpqUd9Date { get; set; }
        public DateTime? OpqUd10Date { get; set; }
        public decimal? OpqUd1Numeric { get; set; }
        public decimal? OpqUd2Numeric { get; set; }
        public decimal? OpqUd3Numeric { get; set; }
        public decimal? OpqUd4Numeric { get; set; }
        public decimal? OpqUd5Numeric { get; set; }
        public decimal? OpqUd6Numeric { get; set; }
        public decimal? OpqUd7Numeric { get; set; }
        public decimal? OpqUd8Numeric { get; set; }
        public decimal? OpqUd9Numeric { get; set; }
        public decimal? OpqUd10Numeric { get; set; }
        public bool? OpqUd1Bit { get; set; }
        public bool? OpqUd2Bit { get; set; }
        public bool? OpqUd3Bit { get; set; }
        public bool? OpqUd4Bit { get; set; }
        public bool? OpqUd5Bit { get; set; }
        public bool? OpqUd6Bit { get; set; }
        public bool? OpqUd7Bit { get; set; }
        public bool? OpqUd8Bit { get; set; }
        public bool? OpqUd9Bit { get; set; }
        public bool? OpqUd10Bit { get; set; }
        public bool? OpqUd11Bit { get; set; }
        public bool? OpqUd12Bit { get; set; }
        public bool? OpqUd13Bit { get; set; }
        public bool? OpqUd14Bit { get; set; }
        public bool? OpqUd15Bit { get; set; }
        public bool? OpqUd16Bit { get; set; }
        public bool? OpqUd17Bit { get; set; }
        public bool? OpqUd18Bit { get; set; }
        public bool? OpqUd19Bit { get; set; }
        public bool? OpqUd20Bit { get; set; }
        public bool? OpqUd21Bit { get; set; }
        public bool? OpqUd22Bit { get; set; }
        public bool? OpqUd23Bit { get; set; }
        public bool? OpqUd24Bit { get; set; }
        public bool? ForcedClose { get; set; }
        public byte? OpqState { get; set; }
        public string OpqUd1IdName { get; set; }
        public string OpqUd2IdName { get; set; }
        public string OpqUd3IdName { get; set; }
        public string OpqUd4IdName { get; set; }
        public string OpqUd5IdName { get; set; }
        public string OpqUd6IdName { get; set; }
        public string OpqUd7IdName { get; set; }
        public string OpqUd8IdName { get; set; }
        public string OpqUd9IdName { get; set; }
        public string OpqUd10IdName { get; set; }
        public string OpqUd1IdNameHlight { get; set; }
        public string OpqUd2IdNameHlight { get; set; }
        public string OpqUd3IdNameHlight { get; set; }
        public string OpqUd4IdNameHlight { get; set; }
        public string OpqUd5IdNameHlight { get; set; }
        public string OpqUd6IdNameHlight { get; set; }
        public string OpqUd7IdNameHlight { get; set; }
        public string OpqUd8IdNameHlight { get; set; }
        public string OpqUd9IdNameHlight { get; set; }
        public string OpqUd10IdNameHlight { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactFax { get; set; }
        public string AccPrefPhone { get; set; }
        public string AccPrefEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BusinessFaxNumberFormatted { get; set; }
        public string AcName { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public Guid? AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AcPhone1 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcCountry { get; set; }
        public string AcPostcode { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcReference { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerDept { get; set; }
        public string OwnerGroup { get; set; }
        public Guid? UsgId { get; set; }
        public string AccountManager { get; set; }
        public string AccountManagerEmail { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcType1 { get; set; }
        public string AcType2 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2Hlight { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string MacIdSourceName { get; set; }
        public Guid? MacIdSource { get; set; }
        public string SourceCampaign { get; set; }
        public Guid? SourceCampaignId { get; set; }
        public string SembUd1Text { get; set; }
        public string SembUd2Text { get; set; }
        public string SembUd3Text { get; set; }
        public string SembUd4Text { get; set; }
        public string SembUd5Text { get; set; }
        public string SembUd6Text { get; set; }
        public string SembUd7Text { get; set; }
        public string SembUd8Text { get; set; }
        public string SembUd9Text { get; set; }
        public string SembUd10Text { get; set; }
        public Guid? SembUd1Id { get; set; }
        public Guid? SembUd2Id { get; set; }
        public Guid? SembUd3Id { get; set; }
        public Guid? SembUd4Id { get; set; }
        public Guid? SembUd5Id { get; set; }
        public Guid? SembUd6Id { get; set; }
        public Guid? SembUd7Id { get; set; }
        public Guid? SembUd8Id { get; set; }
        public Guid? SembUd9Id { get; set; }
        public Guid? SembUd10Id { get; set; }
        public DateTime? SembUd1Date { get; set; }
        public DateTime? SembUd2Date { get; set; }
        public DateTime? SembUd3Date { get; set; }
        public DateTime? SembUd4Date { get; set; }
        public DateTime? SembUd5Date { get; set; }
        public DateTime? SembUd6Date { get; set; }
        public DateTime? SembUd7Date { get; set; }
        public DateTime? SembUd8Date { get; set; }
        public DateTime? SembUd9Date { get; set; }
        public DateTime? SembUd10Date { get; set; }
        public decimal? SembUd1Numeric { get; set; }
        public decimal? SembUd2Numeric { get; set; }
        public decimal? SembUd3Numeric { get; set; }
        public decimal? SembUd4Numeric { get; set; }
        public decimal? SembUd5Numeric { get; set; }
        public decimal? SembUd6Numeric { get; set; }
        public decimal? SembUd7Numeric { get; set; }
        public decimal? SembUd8Numeric { get; set; }
        public decimal? SembUd9Numeric { get; set; }
        public decimal? SembUd10Numeric { get; set; }
        public bool? SembUd1Bit { get; set; }
        public bool? SembUd2Bit { get; set; }
        public bool? SembUd3Bit { get; set; }
        public bool? SembUd4Bit { get; set; }
        public bool? SembUd5Bit { get; set; }
        public bool? SembUd6Bit { get; set; }
        public bool? SembUd7Bit { get; set; }
        public bool? SembUd8Bit { get; set; }
        public bool? SembUd9Bit { get; set; }
        public bool? SembUd10Bit { get; set; }
        public bool? SembUd11Bit { get; set; }
        public bool? SembUd12Bit { get; set; }
        public bool? SembUd13Bit { get; set; }
        public bool? SembUd14Bit { get; set; }
        public bool? SembUd15Bit { get; set; }
        public bool? SembUd16Bit { get; set; }
        public bool? SembUd17Bit { get; set; }
        public bool? SembUd18Bit { get; set; }
        public bool? SembUd19Bit { get; set; }
        public bool? SembUd20Bit { get; set; }
        public bool? SembUd21Bit { get; set; }
        public bool? SembUd22Bit { get; set; }
        public bool? SembUd23Bit { get; set; }
        public bool? SembUd24Bit { get; set; }
        public string SembUd1IdName { get; set; }
        public string SembUd2IdName { get; set; }
        public string SembUd3IdName { get; set; }
        public string SembUd4IdName { get; set; }
        public string SembUd5IdName { get; set; }
        public string SembUd6IdName { get; set; }
        public string SembUd7IdName { get; set; }
        public string SembUd8IdName { get; set; }
        public string SembUd9IdName { get; set; }
        public string SembUd10IdName { get; set; }
        public string FneName { get; set; }
        public Guid? SecurityId { get; set; }
        public string SecurityGroup { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public int? TimeTotal { get; set; }
        public int? UnitsTotal { get; set; }
    }
}
