using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VSeminarsAttendeesAnswer
    {
        public Guid SbaaId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Guid SqId { get; set; }
        public Guid SembId { get; set; }
        public Guid SembaId { get; set; }
        public string Answer { get; set; }
        public string AnswerExtended { get; set; }
        public Guid SemId { get; set; }
        public string Question { get; set; }
        public string QuestionId { get; set; }
        public string GvQuestion { get; set; }
        public string SemSummary { get; set; }
        public string OpenBooking { get; set; }
        public Guid SemsId { get; set; }
        public string SemsSummary { get; set; }
        public Guid AcId { get; set; }
        public decimal? AcPotential { get; set; }
        public decimal AcDiscount { get; set; }
        public string AcFlag { get; set; }
        public string AcUsIdSalesSummary { get; set; }
        public Guid? AcUsIdSales { get; set; }
        public string AcUsIdSupportSummary { get; set; }
        public Guid? AcUsIdSupport { get; set; }
        public string AcType1 { get; set; }
        public string AcType2 { get; set; }
        public string AcSite { get; set; }
        public string AcLabel { get; set; }
        public string AcLevel { get; set; }
        public string AcAccIdSalesSummary { get; set; }
        public Guid? AccIdSales { get; set; }
        public string AccIdSupportSummary { get; set; }
        public Guid? AccIdSupport { get; set; }
        public string AcAddress1 { get; set; }
        public string AcAddress2 { get; set; }
        public string AcAddress3 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcCountry { get; set; }
        public string AcBillingAddress1 { get; set; }
        public string AcBillingAddress2 { get; set; }
        public string AcBillingAddress3 { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcBillingCountry { get; set; }
        public string AcPhone1 { get; set; }
        public string AcPhone2 { get; set; }
        public string AcPhone3 { get; set; }
        public string AcFax1 { get; set; }
        public string AcFax2 { get; set; }
        public string AcFax3 { get; set; }
        public string AcWebSite1 { get; set; }
        public string AcWebSite2 { get; set; }
        public string AcSource { get; set; }
        public string AcIndustry { get; set; }
        public string AcNumberEmployees { get; set; }
        public string AcSummary { get; set; }
        public string AcUd1 { get; set; }
        public string AcUd2 { get; set; }
        public string AcUd3 { get; set; }
        public string AcUd4 { get; set; }
        public string AcUd5 { get; set; }
        public string AcUd6 { get; set; }
        public string AcUd7 { get; set; }
        public string AcUd8 { get; set; }
        public string AcUd9 { get; set; }
        public string AcUd10 { get; set; }
        public string AcUd11 { get; set; }
        public string AcUd12 { get; set; }
        public string AcUd13 { get; set; }
        public string AcUd14 { get; set; }
        public string AcUd15 { get; set; }
        public string AcExternal { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public string AcUd1Id { get; set; }
        public string AcUd2Id { get; set; }
        public string AcUd3Id { get; set; }
        public string AcUd4Id { get; set; }
        public string AcUd5Id { get; set; }
        public string AcUd6Id { get; set; }
        public string AcUd7Id { get; set; }
        public string AcUd8Id { get; set; }
        public string AcUd9Id { get; set; }
        public string AcUd10Id { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public string AcEmailDomains { get; set; }
        public string AcReference { get; set; }
        public string AcLinkedinName { get; set; }
        public Guid AccId { get; set; }
        public string AccTitle { get; set; }
        public string AccFirstname { get; set; }
        public string AccMiddlename { get; set; }
        public string AccLastname { get; set; }
        public string AccJobtitle { get; set; }
        public string AccContactSummary { get; set; }
        public string AccAttendeeSummary { get; set; }
        public string AccAnniversary { get; set; }
        public string AccAssistantname { get; set; }
        public string AccAssistanttelephonenumber { get; set; }
        public string AccBirthday { get; set; }
        public string AccBusinessaddressstreet { get; set; }
        public string AccBusinessaddressstreet2 { get; set; }
        public string AccBusinessaddressstreet3 { get; set; }
        public string AccBusinessaddresscity { get; set; }
        public string AccBusinessaddressstate { get; set; }
        public string AccBusinessaddresspostalcode { get; set; }
        public string AccBusinessaddresscountry { get; set; }
        public string AccBusinessfaxnumber { get; set; }
        public string AccBusinesstelephonenumber { get; set; }
        public string AccCategories { get; set; }
        public string AccDepartment { get; set; }
        public string AccEmail1address { get; set; }
        public string AccEmail2address { get; set; }
        public string AccEmail3address { get; set; }
        public string AccHobby { get; set; }
        public string AccHomeaddressstreet { get; set; }
        public string AccHomeaddressstreet2 { get; set; }
        public string AccHomeaddressstreet3 { get; set; }
        public string AccHomeaddresscity { get; set; }
        public string AccHomeaddressstate { get; set; }
        public string AccHomeaddresspostalcode { get; set; }
        public string AccHomeaddresscountry { get; set; }
        public string AccHomefaxnumber { get; set; }
        public string AccHometelephonenumber { get; set; }
        public string AccManagername { get; set; }
        public string AccMobiletelephonenumber { get; set; }
        public string AccNickname { get; set; }
        public string AccPersonalhomepage { get; set; }
        public string AccReferredby { get; set; }
        public string AccSalutation { get; set; }
        public string AccSuffix { get; set; }
        public string AccSensitivity { get; set; }
        public string AccSpouse { get; set; }
        public string AccWebpage { get; set; }
        public string AccReference { get; set; }
        public string AccUd1 { get; set; }
        public string AccUd2 { get; set; }
        public string AccUd3 { get; set; }
        public string AccUd4 { get; set; }
        public string AccUd5 { get; set; }
        public string AccUd6 { get; set; }
        public string AccUd7 { get; set; }
        public string AccUd8 { get; set; }
        public string AccUd9 { get; set; }
        public string AccUd10 { get; set; }
        public string AccUd11 { get; set; }
        public string AccUd12 { get; set; }
        public string AccUd13 { get; set; }
        public string AccUd14 { get; set; }
        public string AccUd15 { get; set; }
        public bool? AccUd1Bit { get; set; }
        public bool? AccUd2Bit { get; set; }
        public bool? AccUd3Bit { get; set; }
        public bool? AccUd4Bit { get; set; }
        public bool? AccUd5Bit { get; set; }
        public bool? AccUd6Bit { get; set; }
        public bool? AccUd7Bit { get; set; }
        public bool? AccUd8Bit { get; set; }
        public bool? AccUd9Bit { get; set; }
        public bool? AccUd10Bit { get; set; }
        public bool? AccUd11Bit { get; set; }
        public bool? AccUd12Bit { get; set; }
        public bool? AccUd13Bit { get; set; }
        public bool? AccUd14Bit { get; set; }
        public bool? AccUd15Bit { get; set; }
        public bool? AccUd16Bit { get; set; }
        public bool? AccUd17Bit { get; set; }
        public bool? AccUd18Bit { get; set; }
        public bool? AccUd19Bit { get; set; }
        public bool? AccUd20Bit { get; set; }
        public bool? AccUd21Bit { get; set; }
        public bool? AccUd22Bit { get; set; }
        public bool? AccUd23Bit { get; set; }
        public bool? AccUd24Bit { get; set; }
        public string AccUd1Id { get; set; }
        public string AccUd2Id { get; set; }
        public string AccUd3Id { get; set; }
        public string AccUd4Id { get; set; }
        public string AccUd5Id { get; set; }
        public string AccUd6Id { get; set; }
        public string AccUd7Id { get; set; }
        public string AccUd8Id { get; set; }
        public string AccUd9Id { get; set; }
        public string AccUd10Id { get; set; }
        public DateTime? AccUd1Date { get; set; }
        public DateTime? AccUd2Date { get; set; }
        public DateTime? AccUd3Date { get; set; }
        public DateTime? AccUd4Date { get; set; }
        public DateTime? AccUd5Date { get; set; }
        public DateTime? AccUd6Date { get; set; }
        public DateTime? AccUd7Date { get; set; }
        public DateTime? AccUd8Date { get; set; }
        public DateTime? AccUd9Date { get; set; }
        public DateTime? AccUd10Date { get; set; }
        public decimal? AccUd1Numeric { get; set; }
        public decimal? AccUd2Numeric { get; set; }
        public decimal? AccUd3Numeric { get; set; }
        public decimal? AccUd4Numeric { get; set; }
        public decimal? AccUd5Numeric { get; set; }
        public decimal? AccUd6Numeric { get; set; }
        public decimal? AccUd7Numeric { get; set; }
        public decimal? AccUd8Numeric { get; set; }
        public decimal? AccUd9Numeric { get; set; }
        public decimal? AccUd10Numeric { get; set; }
        public string AccExternal { get; set; }
        public string AccStatus { get; set; }
        public bool? PrivacyNotified { get; set; }
        public DateTime? PrivacyNotifiedDate { get; set; }
        public string PrivacyNotifiedBy { get; set; }
        public string PrivacyNotifiedMethod { get; set; }
        public Guid? SemOwner { get; set; }
        public Guid? SgId { get; set; }
        public string ShortCode { get; set; }
    }
}
