using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VSeminarSessionAttendee
    {
        public Guid SemId { get; set; }
        public Guid SembId { get; set; }
        public Guid SembaId { get; set; }
        public Guid AcId { get; set; }
        public Guid? AccId { get; set; }
        public string Details { get; set; }
        public string ShortCode { get; set; }
        public int SembaNumber { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string SembaUd1Text { get; set; }
        public string SembaUd2Text { get; set; }
        public string SembaUd3Text { get; set; }
        public string SembaUd4Text { get; set; }
        public string SembaUd5Text { get; set; }
        public string SembaUd6Text { get; set; }
        public string SembaUd7Text { get; set; }
        public string SembaUd8Text { get; set; }
        public string SembaUd9Text { get; set; }
        public string SembaUd10Text { get; set; }
        public DateTime? SembaUd1Date { get; set; }
        public DateTime? SembaUd2Date { get; set; }
        public DateTime? SembaUd3Date { get; set; }
        public DateTime? SembaUd4Date { get; set; }
        public DateTime? SembaUd5Date { get; set; }
        public DateTime? SembaUd6Date { get; set; }
        public DateTime? SembaUd7Date { get; set; }
        public DateTime? SembaUd8Date { get; set; }
        public DateTime? SembaUd9Date { get; set; }
        public DateTime? SembaUd10Date { get; set; }
        public Guid? SembaUd1Id { get; set; }
        public Guid? SembaUd2Id { get; set; }
        public Guid? SembaUd3Id { get; set; }
        public Guid? SembaUd4Id { get; set; }
        public Guid? SembaUd5Id { get; set; }
        public Guid? SembaUd6Id { get; set; }
        public Guid? SembaUd7Id { get; set; }
        public Guid? SembaUd8Id { get; set; }
        public Guid? SembaUd9Id { get; set; }
        public Guid? SembaUd10Id { get; set; }
        public bool? SembaUd1Bit { get; set; }
        public bool? SembaUd2Bit { get; set; }
        public bool? SembaUd3Bit { get; set; }
        public bool? SembaUd4Bit { get; set; }
        public bool? SembaUd5Bit { get; set; }
        public bool? SembaUd6Bit { get; set; }
        public bool? SembaUd7Bit { get; set; }
        public bool? SembaUd8Bit { get; set; }
        public bool? SembaUd9Bit { get; set; }
        public bool? SembaUd10Bit { get; set; }
        public bool? SembaUd11Bit { get; set; }
        public bool? SembaUd12Bit { get; set; }
        public bool? SembaUd13Bit { get; set; }
        public bool? SembaUd14Bit { get; set; }
        public bool? SembaUd15Bit { get; set; }
        public bool? SembaUd16Bit { get; set; }
        public bool? SembaUd17Bit { get; set; }
        public bool? SembaUd18Bit { get; set; }
        public bool? SembaUd19Bit { get; set; }
        public bool? SembaUd20Bit { get; set; }
        public bool? SembaUd21Bit { get; set; }
        public bool? SembaUd22Bit { get; set; }
        public bool? SembaUd23Bit { get; set; }
        public bool? SembaUd24Bit { get; set; }
        public decimal? SembaUd1Numeric { get; set; }
        public decimal? SembaUd2Numeric { get; set; }
        public decimal? SembaUd3Numeric { get; set; }
        public decimal? SembaUd4Numeric { get; set; }
        public decimal? SembaUd5Numeric { get; set; }
        public decimal? SembaUd6Numeric { get; set; }
        public decimal? SembaUd7Numeric { get; set; }
        public decimal? SembaUd8Numeric { get; set; }
        public decimal? SembaUd9Numeric { get; set; }
        public decimal? SembaUd10Numeric { get; set; }
        public string Reference { get; set; }
        public string ExternalEventbriteId { get; set; }
        public string Summary { get; set; }
        public string SembaOrder { get; set; }
        public bool SembConfirmed { get; set; }
        public DateTime? BookingDate { get; set; }
        public string SembReference { get; set; }
        public string OpenBooking { get; set; }
        public string AcName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Fax1 { get; set; }
        public string SemSummary { get; set; }
        public DateTime? SemStartDate { get; set; }
        public DateTime? SemEndDate { get; set; }
        public string SemUrl { get; set; }
        public string SemSourceDetails { get; set; }
        public string SemType { get; set; }
        public string SemTypeHlight { get; set; }
        public string SemStage { get; set; }
        public string SemStageHlight { get; set; }
        public string SemState { get; set; }
        public string SemReference { get; set; }
        public string SemUd1Text { get; set; }
        public string SemUd2Text { get; set; }
        public string SemUd3Text { get; set; }
        public string SemUd4Text { get; set; }
        public string SemUd5Text { get; set; }
        public string SemUd6Text { get; set; }
        public string SemUd7Text { get; set; }
        public string SemUd8Text { get; set; }
        public string SemUd9Text { get; set; }
        public string SemUd10Text { get; set; }
        public DateTime? SemUd1Date { get; set; }
        public DateTime? SemUd2Date { get; set; }
        public DateTime? SemUd3Date { get; set; }
        public DateTime? SemUd4Date { get; set; }
        public DateTime? SemUd5Date { get; set; }
        public DateTime? SemUd6Date { get; set; }
        public DateTime? SemUd7Date { get; set; }
        public DateTime? SemUd8Date { get; set; }
        public DateTime? SemUd9Date { get; set; }
        public DateTime? SemUd10Date { get; set; }
        public decimal? SemUd1Numeric { get; set; }
        public decimal? SemUd2Numeric { get; set; }
        public decimal? SemUd3Numeric { get; set; }
        public decimal? SemUd4Numeric { get; set; }
        public decimal? SemUd5Numeric { get; set; }
        public decimal? SemUd6Numeric { get; set; }
        public decimal? SemUd7Numeric { get; set; }
        public decimal? SemUd8Numeric { get; set; }
        public decimal? SemUd9Numeric { get; set; }
        public decimal? SemUd10Numeric { get; set; }
        public bool? SemUd1Bit { get; set; }
        public bool? SemUd2Bit { get; set; }
        public bool? SemUd3Bit { get; set; }
        public bool? SemUd4Bit { get; set; }
        public bool? SemUd5Bit { get; set; }
        public bool? SemUd6Bit { get; set; }
        public bool? SemUd7Bit { get; set; }
        public bool? SemUd8Bit { get; set; }
        public bool? SemUd9Bit { get; set; }
        public bool? SemUd10Bit { get; set; }
        public bool? SemUd11Bit { get; set; }
        public bool? SemUd12Bit { get; set; }
        public bool? SemUd13Bit { get; set; }
        public bool? SemUd14Bit { get; set; }
        public bool? SemUd15Bit { get; set; }
        public bool? SemUd16Bit { get; set; }
        public bool? SemUd17Bit { get; set; }
        public bool? SemUd18Bit { get; set; }
        public bool? SemUd19Bit { get; set; }
        public bool? SemUd20Bit { get; set; }
        public bool? SemUd21Bit { get; set; }
        public bool? SemUd22Bit { get; set; }
        public bool? SemUd23Bit { get; set; }
        public bool? SemUd24Bit { get; set; }
        public string SemUd1IdName { get; set; }
        public string SemUd2IdName { get; set; }
        public string SemUd3IdName { get; set; }
        public string SemUd4IdName { get; set; }
        public string SemUd5IdName { get; set; }
        public string SemUd6IdName { get; set; }
        public string SemUd7IdName { get; set; }
        public string SemUd8IdName { get; set; }
        public string SemUd9IdName { get; set; }
        public string SemUd10IdName { get; set; }
        public string SemUd1IdNameHlight { get; set; }
        public string SemUd2IdNameHlight { get; set; }
        public string SemUd3IdNameHlight { get; set; }
        public string SemUd4IdNameHlight { get; set; }
        public string SemUd5IdNameHlight { get; set; }
        public string SemUd6IdNameHlight { get; set; }
        public string SemUd7IdNameHlight { get; set; }
        public string SemUd8IdNameHlight { get; set; }
        public string SemUd9IdNameHlight { get; set; }
        public string SemUd10IdNameHlight { get; set; }
        public string SembUd1Text { get; set; }
        public string SembUd2Text { get; set; }
        public string SembUd3Text { get; set; }
        public string SembUd4Text { get; set; }
        public string SembUd5Text { get; set; }
        public string SembUd6Text { get; set; }
        public string SembUd7Text { get; set; }
        public string SembUd8Text { get; set; }
        public string SembUd9Text { get; set; }
        public string SembUd10Text { get; set; }
        public DateTime? SembUd1Date { get; set; }
        public DateTime? SembUd2Date { get; set; }
        public DateTime? SembUd3Date { get; set; }
        public DateTime? SembUd4Date { get; set; }
        public DateTime? SembUd5Date { get; set; }
        public DateTime? SembUd6Date { get; set; }
        public DateTime? SembUd7Date { get; set; }
        public DateTime? SembUd8Date { get; set; }
        public DateTime? SembUd9Date { get; set; }
        public DateTime? SembUd10Date { get; set; }
        public decimal? SembUd1Numeric { get; set; }
        public decimal? SembUd2Numeric { get; set; }
        public decimal? SembUd3Numeric { get; set; }
        public decimal? SembUd4Numeric { get; set; }
        public decimal? SembUd5Numeric { get; set; }
        public decimal? SembUd6Numeric { get; set; }
        public decimal? SembUd7Numeric { get; set; }
        public decimal? SembUd8Numeric { get; set; }
        public decimal? SembUd9Numeric { get; set; }
        public decimal? SembUd10Numeric { get; set; }
        public bool? SembUd1Bit { get; set; }
        public bool? SembUd2Bit { get; set; }
        public bool? SembUd3Bit { get; set; }
        public bool? SembUd4Bit { get; set; }
        public bool? SembUd5Bit { get; set; }
        public bool? SembUd6Bit { get; set; }
        public bool? SembUd7Bit { get; set; }
        public bool? SembUd8Bit { get; set; }
        public bool? SembUd9Bit { get; set; }
        public bool? SembUd10Bit { get; set; }
        public bool? SembUd11Bit { get; set; }
        public bool? SembUd12Bit { get; set; }
        public bool? SembUd13Bit { get; set; }
        public bool? SembUd14Bit { get; set; }
        public bool? SembUd15Bit { get; set; }
        public bool? SembUd16Bit { get; set; }
        public bool? SembUd17Bit { get; set; }
        public bool? SembUd18Bit { get; set; }
        public bool? SembUd19Bit { get; set; }
        public bool? SembUd20Bit { get; set; }
        public bool? SembUd21Bit { get; set; }
        public bool? SembUd22Bit { get; set; }
        public bool? SembUd23Bit { get; set; }
        public bool? SembUd24Bit { get; set; }
        public string SembUd1IdName { get; set; }
        public string SembUd2IdName { get; set; }
        public string SembUd3IdName { get; set; }
        public string SembUd4IdName { get; set; }
        public string SembUd5IdName { get; set; }
        public string SembUd6IdName { get; set; }
        public string SembUd7IdName { get; set; }
        public string SembUd8IdName { get; set; }
        public string SembUd9IdName { get; set; }
        public string SembUd10IdName { get; set; }
        public string SembUd1IdNameHlight { get; set; }
        public string SembUd2IdNameHlight { get; set; }
        public string SembUd3IdNameHlight { get; set; }
        public string SembUd4IdNameHlight { get; set; }
        public string SembUd5IdNameHlight { get; set; }
        public string SembUd6IdNameHlight { get; set; }
        public string SembUd7IdNameHlight { get; set; }
        public string SembUd8IdNameHlight { get; set; }
        public string SembUd9IdNameHlight { get; set; }
        public string SembUd10IdNameHlight { get; set; }
        public string AccName { get; set; }
        public string Email1Address { get; set; }
        public string AccBusinessAddressStreet { get; set; }
        public string AccBusinessAddressStreet2 { get; set; }
        public string AccBusinessAddressStreet3 { get; set; }
        public string AccBusinessAddressCity { get; set; }
        public string AccBusinessAddressState { get; set; }
        public string AccBusinessAddressPostalCode { get; set; }
        public string AccBusinessAddressCountry { get; set; }
        public string AccBusinessFaxNumber { get; set; }
        public string AccEmail1address { get; set; }
        public string AccBusinesstelephonenumber { get; set; }
        public string AccMobiletelephonenumber { get; set; }
        public string AccJobtitle { get; set; }
        public Guid? SembAccId { get; set; }
        public string SembAccName { get; set; }
        public string SembAccBusinessAddressStreet { get; set; }
        public string SembAccBusinessAddressStreet2 { get; set; }
        public string SembAccBusinessAddressStreet3 { get; set; }
        public string SembAccBusinessAddressCity { get; set; }
        public string SembAccBusinessAddressState { get; set; }
        public string SembAccBusinessAddressPostalCode { get; set; }
        public string SembAccBusinessAddressCountry { get; set; }
        public string SembAccBusinessFaxNumber { get; set; }
        public string SembAccEmail1address { get; set; }
        public string SembAccBusinesstelephonenumber { get; set; }
        public string SembAccMobiletelephonenumber { get; set; }
        public string SembAccJobtitle { get; set; }
        public string AccUd1 { get; set; }
        public string AccUd2 { get; set; }
        public string AccUd3 { get; set; }
        public string AccUd4 { get; set; }
        public string AccUd5 { get; set; }
        public string AccUd6 { get; set; }
        public string AccUd7 { get; set; }
        public string AccUd8 { get; set; }
        public string AccUd9 { get; set; }
        public string AccUd10 { get; set; }
        public string AccUd11 { get; set; }
        public string AccUd12 { get; set; }
        public string AccUd13 { get; set; }
        public string AccUd14 { get; set; }
        public string AccUd15 { get; set; }
        public Guid? AccUd1Id { get; set; }
        public Guid? AccUd2Id { get; set; }
        public Guid? AccUd3Id { get; set; }
        public Guid? AccUd4Id { get; set; }
        public Guid? AccUd5Id { get; set; }
        public Guid? AccUd6Id { get; set; }
        public Guid? AccUd7Id { get; set; }
        public Guid? AccUd8Id { get; set; }
        public Guid? AccUd9Id { get; set; }
        public Guid? AccUd10Id { get; set; }
        public DateTime? AccUd1Date { get; set; }
        public DateTime? AccUd2Date { get; set; }
        public DateTime? AccUd3Date { get; set; }
        public DateTime? AccUd4Date { get; set; }
        public DateTime? AccUd5Date { get; set; }
        public DateTime? AccUd6Date { get; set; }
        public DateTime? AccUd7Date { get; set; }
        public DateTime? AccUd8Date { get; set; }
        public DateTime? AccUd9Date { get; set; }
        public DateTime? AccUd10Date { get; set; }
        public bool? AccUd1Bit { get; set; }
        public bool? AccUd2Bit { get; set; }
        public bool? AccUd3Bit { get; set; }
        public bool? AccUd4Bit { get; set; }
        public bool? AccUd5Bit { get; set; }
        public bool? AccUd6Bit { get; set; }
        public bool? AccUd7Bit { get; set; }
        public bool? AccUd8Bit { get; set; }
        public bool? AccUd9Bit { get; set; }
        public bool? AccUd10Bit { get; set; }
        public bool? AccUd11Bit { get; set; }
        public bool? AccUd12Bit { get; set; }
        public bool? AccUd13Bit { get; set; }
        public bool? AccUd14Bit { get; set; }
        public bool? AccUd15Bit { get; set; }
        public bool? AccUd16Bit { get; set; }
        public bool? AccUd17Bit { get; set; }
        public bool? AccUd18Bit { get; set; }
        public bool? AccUd19Bit { get; set; }
        public bool? AccUd20Bit { get; set; }
        public bool? AccUd21Bit { get; set; }
        public bool? AccUd22Bit { get; set; }
        public bool? AccUd23Bit { get; set; }
        public bool? AccUd24Bit { get; set; }
        public decimal? AccUd1Numeric { get; set; }
        public decimal? AccUd2Numeric { get; set; }
        public decimal? AccUd3Numeric { get; set; }
        public decimal? AccUd4Numeric { get; set; }
        public decimal? AccUd5Numeric { get; set; }
        public decimal? AccUd6Numeric { get; set; }
        public decimal? AccUd7Numeric { get; set; }
        public decimal? AccUd8Numeric { get; set; }
        public decimal? AccUd9Numeric { get; set; }
        public decimal? AccUd10Numeric { get; set; }
        public string AccUd1IdName { get; set; }
        public string AccUd2IdName { get; set; }
        public string AccUd3IdName { get; set; }
        public string AccUd4IdName { get; set; }
        public string AccUd5IdName { get; set; }
        public string AccUd6IdName { get; set; }
        public string AccUd7IdName { get; set; }
        public string AccUd8IdName { get; set; }
        public string AccUd9IdName { get; set; }
        public string AccUd10IdName { get; set; }
        public string AccUd1IdNameHlight { get; set; }
        public string AccUd2IdNameHlight { get; set; }
        public string AccUd3IdNameHlight { get; set; }
        public string AccUd4IdNameHlight { get; set; }
        public string AccUd5IdNameHlight { get; set; }
        public string AccUd6IdNameHlight { get; set; }
        public string AccUd7IdNameHlight { get; set; }
        public string AccUd8IdNameHlight { get; set; }
        public string AccUd9IdNameHlight { get; set; }
        public string AccUd10IdNameHlight { get; set; }
        public int BookedSessions { get; set; }
        public string SembaUd1IdName { get; set; }
        public string SembaUd2IdName { get; set; }
        public string SembaUd3IdName { get; set; }
        public string SembaUd4IdName { get; set; }
        public string SembaUd5IdName { get; set; }
        public string SembaUd6IdName { get; set; }
        public string SembaUd7IdName { get; set; }
        public string SembaUd8IdName { get; set; }
        public string SembaUd9IdName { get; set; }
        public string SembaUd10IdName { get; set; }
        public string SembaUd1IdNameHlight { get; set; }
        public string SembaUd2IdNameHlight { get; set; }
        public string SembaUd3IdNameHlight { get; set; }
        public string SembaUd4IdNameHlight { get; set; }
        public string SembaUd5IdNameHlight { get; set; }
        public string SembaUd6IdNameHlight { get; set; }
        public string SembaUd7IdNameHlight { get; set; }
        public string SembaUd8IdNameHlight { get; set; }
        public string SembaUd9IdNameHlight { get; set; }
        public string SembaUd10IdNameHlight { get; set; }
        public string AcType1 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2 { get; set; }
        public string AcType2Hlight { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public Guid? SemOwner { get; set; }
        public Guid? SgId { get; set; }
        public byte? SembState { get; set; }
        public string AcExternal { get; set; }
        public Guid SemsaId { get; set; }
        public Guid SemsId { get; set; }
        public string SemsName { get; set; }
        public string SemsCode { get; set; }
        public string SemsLocation { get; set; }
        public decimal SemsPrice { get; set; }
        public DateTime? SemsStartDate { get; set; }
        public DateTime? SemsEndDate { get; set; }
        public int? SemsDay { get; set; }
        public int? CsId { get; set; }
        public string LeadSummary { get; set; }
        public Guid BookingId { get; set; }
    }
}
