using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VSeminarBooking
    {
        public Guid? SemId { get; set; }
        public Guid SembId { get; set; }
        public bool SembDeleted { get; set; }
        public Guid AcId { get; set; }
        public Guid? AccId { get; set; }
        public string Details { get; set; }
        public string ShortCode { get; set; }
        public bool Confirmed { get; set; }
        public decimal Value { get; set; }
        public double NumberOfItems { get; set; }
        public decimal CostItems { get; set; }
        public double DiscountItems { get; set; }
        public decimal CostBooking { get; set; }
        public double DiscountAccount { get; set; }
        public decimal CostSub { get; set; }
        public decimal CostUpdatedSub { get; set; }
        public decimal CostVat { get; set; }
        public decimal CostTotal { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string SembUd1Text { get; set; }
        public string SembUd2Text { get; set; }
        public string SembUd3Text { get; set; }
        public string SembUd4Text { get; set; }
        public string SembUd5Text { get; set; }
        public string SembUd6Text { get; set; }
        public string SembUd7Text { get; set; }
        public string SembUd8Text { get; set; }
        public string SembUd9Text { get; set; }
        public string SembUd10Text { get; set; }
        public DateTime? SembUd1Date { get; set; }
        public DateTime? SembUd2Date { get; set; }
        public DateTime? SembUd3Date { get; set; }
        public DateTime? SembUd4Date { get; set; }
        public DateTime? SembUd5Date { get; set; }
        public DateTime? SembUd6Date { get; set; }
        public DateTime? SembUd7Date { get; set; }
        public DateTime? SembUd8Date { get; set; }
        public DateTime? SembUd9Date { get; set; }
        public DateTime? SembUd10Date { get; set; }
        public Guid? SembUd1Id { get; set; }
        public Guid? SembUd2Id { get; set; }
        public Guid? SembUd3Id { get; set; }
        public Guid? SembUd4Id { get; set; }
        public Guid? SembUd5Id { get; set; }
        public Guid? SembUd6Id { get; set; }
        public Guid? SembUd7Id { get; set; }
        public Guid? SembUd8Id { get; set; }
        public Guid? SembUd9Id { get; set; }
        public Guid? SembUd10Id { get; set; }
        public bool? SembUd1Bit { get; set; }
        public bool? SembUd2Bit { get; set; }
        public bool? SembUd3Bit { get; set; }
        public bool? SembUd4Bit { get; set; }
        public bool? SembUd5Bit { get; set; }
        public bool? SembUd6Bit { get; set; }
        public bool? SembUd7Bit { get; set; }
        public bool? SembUd8Bit { get; set; }
        public bool? SembUd9Bit { get; set; }
        public bool? SembUd10Bit { get; set; }
        public bool? SembUd11Bit { get; set; }
        public bool? SembUd12Bit { get; set; }
        public bool? SembUd13Bit { get; set; }
        public bool? SembUd14Bit { get; set; }
        public bool? SembUd15Bit { get; set; }
        public bool? SembUd16Bit { get; set; }
        public bool? SembUd17Bit { get; set; }
        public bool? SembUd18Bit { get; set; }
        public bool? SembUd19Bit { get; set; }
        public bool? SembUd20Bit { get; set; }
        public bool? SembUd21Bit { get; set; }
        public bool? SembUd22Bit { get; set; }
        public bool? SembUd23Bit { get; set; }
        public bool? SembUd24Bit { get; set; }
        public decimal? SembUd1Numeric { get; set; }
        public decimal? SembUd2Numeric { get; set; }
        public decimal? SembUd3Numeric { get; set; }
        public decimal? SembUd4Numeric { get; set; }
        public decimal? SembUd5Numeric { get; set; }
        public decimal? SembUd6Numeric { get; set; }
        public decimal? SembUd7Numeric { get; set; }
        public decimal? SembUd8Numeric { get; set; }
        public decimal? SembUd9Numeric { get; set; }
        public decimal? SembUd10Numeric { get; set; }
        public string Reference { get; set; }
        public int? ReferenceSeed { get; set; }
        public byte? SembState { get; set; }
        public Guid? CurIdPriceList { get; set; }
        public DateTime? ActualClose { get; set; }
        public DateTime? EstimatedClose { get; set; }
        public Guid? FneId { get; set; }
        public Guid? McaId { get; set; }
        public Guid? StgId { get; set; }
        public string ExternalEventbriteId { get; set; }
        public Guid? Owner { get; set; }
        public string SemName { get; set; }
        public DateTime? SemStartDate { get; set; }
        public DateTime? SemEndDate { get; set; }
        public string SemState { get; set; }
        public string State { get; set; }
        public string SemReference { get; set; }
        public Guid? SemStgId { get; set; }
        public string SemUrl { get; set; }
        public string SemSourceDetails { get; set; }
        public string SemType { get; set; }
        public string AcName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string Phone1 { get; set; }
        public string Fax1 { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public bool? AcUd11Bit { get; set; }
        public bool? AcUd12Bit { get; set; }
        public bool? AcUd13Bit { get; set; }
        public bool? AcUd14Bit { get; set; }
        public bool? AcUd15Bit { get; set; }
        public bool? AcUd16Bit { get; set; }
        public bool? AcUd17Bit { get; set; }
        public bool? AcUd18Bit { get; set; }
        public bool? AcUd19Bit { get; set; }
        public bool? AcUd20Bit { get; set; }
        public bool? AcUd21Bit { get; set; }
        public bool? AcUd22Bit { get; set; }
        public bool? AcUd23Bit { get; set; }
        public bool? AcUd24Bit { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public string AcUd1IdName { get; set; }
        public string AcUd1IdNameHlight { get; set; }
        public string AcUd2IdName { get; set; }
        public string AcUd2IdNameHlight { get; set; }
        public string AcUd3IdName { get; set; }
        public string AcUd3IdNameHlight { get; set; }
        public string AcUd4IdName { get; set; }
        public string AcUd4IdNameHlight { get; set; }
        public string AcUd5IdName { get; set; }
        public string AcUd5IdNameHlight { get; set; }
        public string AcUd6IdName { get; set; }
        public string AcUd6IdNameHlight { get; set; }
        public string AcUd7IdName { get; set; }
        public string AcUd7IdNameHlight { get; set; }
        public string AcUd8IdName { get; set; }
        public string AcUd8IdNameHlight { get; set; }
        public string AcUd9IdName { get; set; }
        public string AcUd9IdNameHlight { get; set; }
        public string AcUd10IdName { get; set; }
        public string AcUd10IdNameHlight { get; set; }
        public string AcUd1Id { get; set; }
        public string AcUd2Id { get; set; }
        public string AcUd3Id { get; set; }
        public string AcUd4Id { get; set; }
        public string AcUd5Id { get; set; }
        public string AcUd6Id { get; set; }
        public string AcUd7Id { get; set; }
        public string AcUd8Id { get; set; }
        public string AcUd9Id { get; set; }
        public string AcUd10Id { get; set; }
        public string AccName { get; set; }
        public string Email1Address { get; set; }
        public int? Attendees { get; set; }
        public string Booking { get; set; }
        public string SembUd1IdName { get; set; }
        public string SembUd2IdName { get; set; }
        public string SembUd3IdName { get; set; }
        public string SembUd4IdName { get; set; }
        public string SembUd5IdName { get; set; }
        public string SembUd6IdName { get; set; }
        public string SembUd7IdName { get; set; }
        public string SembUd8IdName { get; set; }
        public string SembUd9IdName { get; set; }
        public string SembUd10IdName { get; set; }
        public string SembUd1IdNameHlight { get; set; }
        public string SembUd2IdNameHlight { get; set; }
        public string SembUd3IdNameHlight { get; set; }
        public string SembUd4IdNameHlight { get; set; }
        public string SembUd5IdNameHlight { get; set; }
        public string SembUd6IdNameHlight { get; set; }
        public string SembUd7IdNameHlight { get; set; }
        public string SembUd8IdNameHlight { get; set; }
        public string SembUd9IdNameHlight { get; set; }
        public string SembUd10IdNameHlight { get; set; }
        public string AcType1 { get; set; }
        public string AcType1Hlight { get; set; }
        public string AcType2 { get; set; }
        public string AcType2Hlight { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string CurrencySymbol { get; set; }
        public string CurrencyCode { get; set; }
        public double CurrencyRate { get; set; }
        public DateTime? ForecastDate { get; set; }
        public string UsName { get; set; }
        public Guid? UsId { get; set; }
        public string OwnerEmail { get; set; }
        public string UsgName { get; set; }
        public Guid? UsgId { get; set; }
        public string CampaignSummary { get; set; }
        public string StageSummary { get; set; }
        public Guid? SemOwner { get; set; }
        public Guid? SgId { get; set; }
        public string AcExternal { get; set; }
        public Guid? AcManager { get; set; }
        public Guid? AcgId { get; set; }
        public decimal? OriginalClosedWonTotal { get; set; }
        public DateTime? OriginalClosedWonDate { get; set; }
        public Guid CurId { get; set; }
    }
}
