using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VSite
    {
        public Guid SitId { get; set; }
        public Guid AcId { get; set; }
        public Guid? AccId { get; set; }
        public string Summary { get; set; }
        public Guid? UsId { get; set; }
        public string UsName { get; set; }
        public string UsgName { get; set; }
        public string AcName { get; set; }
        public string AccName { get; set; }
        public Guid? AcgId { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string Type1Name { get; set; }
        public Guid? Type1 { get; set; }
        public string Phone1 { get; set; }
        public string Fax1 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string SitExternal { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string WebSite1 { get; set; }
        public string TimeZone { get; set; }
        public string SitUd1 { get; set; }
        public string SitUd2 { get; set; }
        public string SitUd3 { get; set; }
        public string SitUd4 { get; set; }
        public string SitUd5 { get; set; }
        public string SitUd6 { get; set; }
        public string SitUd7 { get; set; }
        public string SitUd8 { get; set; }
        public string SitUd9 { get; set; }
        public string SitUd10 { get; set; }
        public string SitUd11 { get; set; }
        public string SitUd12 { get; set; }
        public string SitUd13 { get; set; }
        public string SitUd14 { get; set; }
        public string SitUd15 { get; set; }
        public Guid? SitUd1Id { get; set; }
        public Guid? SitUd2Id { get; set; }
        public Guid? SitUd3Id { get; set; }
        public Guid? SitUd4Id { get; set; }
        public Guid? SitUd5Id { get; set; }
        public Guid? SitUd6Id { get; set; }
        public Guid? SitUd7Id { get; set; }
        public Guid? SitUd8Id { get; set; }
        public Guid? SitUd9Id { get; set; }
        public Guid? SitUd10Id { get; set; }
        public string SitUd1IdName { get; set; }
        public string SitUd2IdName { get; set; }
        public string SitUd3IdName { get; set; }
        public string SitUd4IdName { get; set; }
        public string SitUd5IdName { get; set; }
        public string SitUd6IdName { get; set; }
        public string SitUd7IdName { get; set; }
        public string SitUd8IdName { get; set; }
        public string SitUd9IdName { get; set; }
        public string SitUd10IdName { get; set; }
        public DateTime? SitUd1Date { get; set; }
        public DateTime? SitUd2Date { get; set; }
        public DateTime? SitUd3Date { get; set; }
        public DateTime? SitUd4Date { get; set; }
        public DateTime? SitUd5Date { get; set; }
        public DateTime? SitUd6Date { get; set; }
        public DateTime? SitUd7Date { get; set; }
        public DateTime? SitUd8Date { get; set; }
        public DateTime? SitUd9Date { get; set; }
        public DateTime? SitUd10Date { get; set; }
        public bool? SitUd1Bit { get; set; }
        public bool? SitUd2Bit { get; set; }
        public bool? SitUd3Bit { get; set; }
        public bool? SitUd4Bit { get; set; }
        public bool? SitUd5Bit { get; set; }
        public bool? SitUd6Bit { get; set; }
        public bool? SitUd7Bit { get; set; }
        public bool? SitUd8Bit { get; set; }
        public bool? SitUd9Bit { get; set; }
        public bool? SitUd10Bit { get; set; }
        public bool? SitUd11Bit { get; set; }
        public bool? SitUd12Bit { get; set; }
        public bool? SitUd13Bit { get; set; }
        public bool? SitUd14Bit { get; set; }
        public bool? SitUd15Bit { get; set; }
        public bool? SitUd16Bit { get; set; }
        public bool? SitUd17Bit { get; set; }
        public bool? SitUd18Bit { get; set; }
        public bool? SitUd19Bit { get; set; }
        public bool? SitUd20Bit { get; set; }
        public bool? SitUd21Bit { get; set; }
        public bool? SitUd22Bit { get; set; }
        public bool? SitUd23Bit { get; set; }
        public bool? SitUd24Bit { get; set; }
        public decimal? SitUd1Numeric { get; set; }
        public decimal? SitUd2Numeric { get; set; }
        public decimal? SitUd3Numeric { get; set; }
        public decimal? SitUd4Numeric { get; set; }
        public decimal? SitUd5Numeric { get; set; }
        public decimal? SitUd6Numeric { get; set; }
        public decimal? SitUd7Numeric { get; set; }
        public decimal? SitUd8Numeric { get; set; }
        public decimal? SitUd9Numeric { get; set; }
        public decimal? SitUd10Numeric { get; set; }
        public string LinkedinPublicId { get; set; }
        public string LinkedinPrivateId { get; set; }
        public string LinkedinProfileUrl { get; set; }
        public string LinkedinImage { get; set; }
        public string LinkedinName { get; set; }
        public string FacebookPublicId { get; set; }
        public string FacebookPrivateId { get; set; }
        public string FacebookProfileUrl { get; set; }
        public string FacebookImage { get; set; }
        public string FacebookName { get; set; }
        public string GplusPublicId { get; set; }
        public string GplusPrivateId { get; set; }
        public string GplusProfileUrl { get; set; }
        public string GplusImage { get; set; }
        public string GplusName { get; set; }
        public string Twitter1PublicId { get; set; }
        public string Twitter1PrivateId { get; set; }
        public string Twitter1ProfileUrl { get; set; }
        public string Twitter1Image { get; set; }
        public string Twitter1Name { get; set; }
        public string Twitter2PublicId { get; set; }
        public string Twitter2PrivateId { get; set; }
        public string Twitter2ProfileUrl { get; set; }
        public string Twitter2Image { get; set; }
        public string Twitter2Name { get; set; }
        public string Twitter3PublicId { get; set; }
        public string Twitter3PrivateId { get; set; }
        public string Twitter3ProfileUrl { get; set; }
        public string Twitter3Image { get; set; }
        public string Twitter3Name { get; set; }
        public string Twitter4PublicId { get; set; }
        public string Twitter4PrivateId { get; set; }
        public string Twitter4ProfileUrl { get; set; }
        public string Twitter4Image { get; set; }
        public string Twitter4Name { get; set; }
        public string Twitter5PublicId { get; set; }
        public string Twitter5PrivateId { get; set; }
        public string Twitter5ProfileUrl { get; set; }
        public string Twitter5Image { get; set; }
        public string Twitter5Name { get; set; }
        public string Type1NameHlight { get; set; }
        public string SitUd1IdNameHlight { get; set; }
        public string SitUd2IdNameHlight { get; set; }
        public string SitUd3IdNameHlight { get; set; }
        public string SitUd4IdNameHlight { get; set; }
        public string SitUd5IdNameHlight { get; set; }
        public string SitUd6IdNameHlight { get; set; }
        public string SitUd7IdNameHlight { get; set; }
        public string SitUd8IdNameHlight { get; set; }
        public string SitUd9IdNameHlight { get; set; }
        public string SitUd10IdNameHlight { get; set; }
        public string Fax1Formatted { get; set; }
        public string ShortCode { get; set; }
    }
}
