using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VUsersHome
    {
        public Guid? UsgId { get; set; }
        public Guid UsId { get; set; }
        public bool UsDeleted { get; set; }
        public Guid? Manager { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public string Exchangeid { get; set; }
        public string EmailAddress { get; set; }
        public string NtAccount { get; set; }
        public string ExchangeServer { get; set; }
        public DateTime? LastScanned { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string DeletedBy { get; set; }
        public string UsUd1 { get; set; }
        public string UsUd2 { get; set; }
        public string UsUd3 { get; set; }
        public string UsUd4 { get; set; }
        public string UsUd5 { get; set; }
        public string UsUd6 { get; set; }
        public string UsUd7 { get; set; }
        public string UsUd8 { get; set; }
        public string UsUd9 { get; set; }
        public string UsUd10 { get; set; }
        public string UsUd11 { get; set; }
        public string UsUd12 { get; set; }
        public string UsUd13 { get; set; }
        public string UsUd14 { get; set; }
        public string UsUd15 { get; set; }
        public bool? Admin { get; set; }
        public bool? Sales { get; set; }
        public bool? Email { get; set; }
        public bool? Home { get; set; }
        public string AName { get; set; }
        public string ARef { get; set; }
        public string BName { get; set; }
        public string BRef { get; set; }
        public string CName { get; set; }
        public string CRef { get; set; }
        public string HomeName { get; set; }
        public string HomeRef { get; set; }
        public string UserJobTitle { get; set; }
        public string UserDirectPhone { get; set; }
        public string UserMobileTelephone { get; set; }
        public string UserDepartment { get; set; }
        public string TemplateFolder { get; set; }
        public string HashedPwd { get; set; }
        public Guid? SetIdPhone { get; set; }
        public bool? UseWordMailMerge { get; set; }
        public string PhoneCountryCode { get; set; }
        public string PhoneIddCode { get; set; }
        public string PhoneNddCode { get; set; }
        public string PhoneOutsideLineCode { get; set; }
        public Guid? CtId { get; set; }
        public short? TimeDiff { get; set; }
        public bool? RootUser { get; set; }
        public decimal MonthlySalesTarget { get; set; }
        public string AddressLookupDetails { get; set; }
        public string EmailScanDetails { get; set; }
        public string EmailScanFolders { get; set; }
        public string EmailScanExclusions { get; set; }
        public bool? EmailScanEmails { get; set; }
        public bool? EmailScanContacts { get; set; }
        public bool? EmailScanAppointments { get; set; }
        public bool? EmailScanTasks { get; set; }
        public int? EmailScanMaxSensitivity { get; set; }
        public string Lang { get; set; }
        public string UsExternal { get; set; }
        public bool? AccessEnabled { get; set; }
        public bool? AccessAdmin { get; set; }
        public bool? ShowOnUsers { get; set; }
        public bool? ShowOnAcManager { get; set; }
        public bool? ShowOnSupport { get; set; }
        public Guid? UsUd1Id { get; set; }
        public Guid? UsUd2Id { get; set; }
        public Guid? UsUd3Id { get; set; }
        public Guid? UsUd4Id { get; set; }
        public Guid? UsUd5Id { get; set; }
        public Guid? UsUd6Id { get; set; }
        public Guid? UsUd7Id { get; set; }
        public Guid? UsUd8Id { get; set; }
        public Guid? UsUd9Id { get; set; }
        public Guid? UsUd10Id { get; set; }
        public DateTime? UsUd1Date { get; set; }
        public DateTime? UsUd2Date { get; set; }
        public DateTime? UsUd3Date { get; set; }
        public DateTime? UsUd4Date { get; set; }
        public DateTime? UsUd5Date { get; set; }
        public DateTime? UsUd6Date { get; set; }
        public DateTime? UsUd7Date { get; set; }
        public DateTime? UsUd8Date { get; set; }
        public DateTime? UsUd9Date { get; set; }
        public DateTime? UsUd10Date { get; set; }
        public decimal? UsUd1Numeric { get; set; }
        public decimal? UsUd2Numeric { get; set; }
        public decimal? UsUd3Numeric { get; set; }
        public decimal? UsUd4Numeric { get; set; }
        public decimal? UsUd5Numeric { get; set; }
        public decimal? UsUd6Numeric { get; set; }
        public decimal? UsUd7Numeric { get; set; }
        public decimal? UsUd8Numeric { get; set; }
        public decimal? UsUd9Numeric { get; set; }
        public decimal? UsUd10Numeric { get; set; }
        public bool? UsUd1Bit { get; set; }
        public bool? UsUd2Bit { get; set; }
        public bool? UsUd3Bit { get; set; }
        public bool? UsUd4Bit { get; set; }
        public bool? UsUd5Bit { get; set; }
        public bool? UsUd6Bit { get; set; }
        public bool? UsUd7Bit { get; set; }
        public bool? UsUd8Bit { get; set; }
        public bool? UsUd9Bit { get; set; }
        public bool? UsUd10Bit { get; set; }
        public bool? UsUd11Bit { get; set; }
        public bool? UsUd12Bit { get; set; }
        public bool? UsUd13Bit { get; set; }
        public bool? UsUd14Bit { get; set; }
        public bool? UsUd15Bit { get; set; }
        public bool? UsUd16Bit { get; set; }
        public bool? UsUd17Bit { get; set; }
        public bool? UsUd18Bit { get; set; }
        public bool? UsUd19Bit { get; set; }
        public bool? UsUd20Bit { get; set; }
        public bool? UsUd21Bit { get; set; }
        public bool? UsUd22Bit { get; set; }
        public bool? UsUd23Bit { get; set; }
        public bool? UsUd24Bit { get; set; }
        public string DateFormat { get; set; }
        public string NumberFormat { get; set; }
        public Guid? CurId { get; set; }
        public bool? SingleWindow { get; set; }
        public bool? PrivateEmail { get; set; }
        public bool? SimpleViewMenu { get; set; }
        public int? CsIdLatest { get; set; }
        public DateTime? CsLatestDate { get; set; }
        public string TimeZone { get; set; }
        public bool? ShowOnCalendar { get; set; }
        public bool? EnableServerDocProd { get; set; }
        public bool? MapsAccess { get; set; }
        public string LivechatEmail { get; set; }
        public Guid? UsCulture { get; set; }
        public Guid? LangId { get; set; }
        public string CultureCode { get; set; }
        public bool IsActionCentrePinned { get; set; }
        public Guid? AcoTeamId { get; set; }
        public int? EsteiroidentSid { get; set; }
        public bool IsMenuExpanded { get; set; }
        public bool HybridEnabled { get; set; }
        public Guid HybridDefaultMode { get; set; }
        public bool? NoAccess { get; set; }
        public string UserGroupName { get; set; }
        public Guid UsIdDeleted { get; set; }
        public string PhoneSettings { get; set; }
        public string UsUd1IdName { get; set; }
        public string UsUd2IdName { get; set; }
        public string UsUd3IdName { get; set; }
        public string UsUd4IdName { get; set; }
        public string UsUd5IdName { get; set; }
        public string UsUd6IdName { get; set; }
        public string UsUd7IdName { get; set; }
        public string UsUd8IdName { get; set; }
        public string UsUd9IdName { get; set; }
        public string UsUd10IdName { get; set; }
        public string UsUd1IdNameHlight { get; set; }
        public string UsUd2IdNameHlight { get; set; }
        public string UsUd3IdNameHlight { get; set; }
        public string UsUd4IdNameHlight { get; set; }
        public string UsUd5IdNameHlight { get; set; }
        public string UsUd6IdNameHlight { get; set; }
        public string UsUd7IdNameHlight { get; set; }
        public string UsUd8IdNameHlight { get; set; }
        public string UsUd9IdNameHlight { get; set; }
        public string UsUd10IdNameHlight { get; set; }
        public string LicenceTypeName { get; set; }
        public Guid? UserGroupId { get; set; }
        public string ShortCode { get; set; }
    }
}
