using System;
using System.Collections.Generic;

#nullable disable

namespace Proactive.Models.Maguire
{
    public partial class VUsersAppointment
    {
        public Guid? AcId { get; set; }
        public Guid? AccId { get; set; }
        public Guid UsaId { get; set; }
        public bool UsaDeleted { get; set; }
        public string UsaMapiId { get; set; }
        public string UsaStoreId { get; set; }
        public string Subject { get; set; }
        public string Summary { get; set; }
        public DateTime? Start { get; set; }
        public DateTime? End { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? DueDate { get; set; }
        public bool? AllDay { get; set; }
        public string Location { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ParentType { get; set; }
        public string ParentTypeName { get; set; }
        public string Details { get; set; }
        public bool? GoneFromOutlook { get; set; }
        public bool? Recurring { get; set; }
        public bool UtcConverted { get; set; }
        public int? RecurrenceType { get; set; }
        public string RecurrenceInfo { get; set; }
        public int? ReminderMinutes { get; set; }
        public string Reference { get; set; }
        public Guid? ActId { get; set; }
        public Guid? PjId { get; set; }
        public Guid? OpId { get; set; }
        public Guid? UsId { get; set; }
        public string Owner { get; set; }
        public string OwnerName { get; set; }
        public string OwnerDept { get; set; }
        public Guid? UsgId { get; set; }
        public string OwnerGroup { get; set; }
        public string NtAccount { get; set; }
        public string Exchangeid { get; set; }
        public string Mailbox { get; set; }
        public string AcName { get; set; }
        public string AccName { get; set; }
        public string AccBusinessTelephoneNumber { get; set; }
        public string AccEmail1Address { get; set; }
        public Guid? UsIdSales { get; set; }
        public Guid? UsIdSupport { get; set; }
        public string AcType { get; set; }
        public string AcType2 { get; set; }
        public string AcTypeHlight { get; set; }
        public string AcType2Hlight { get; set; }
        public Guid AcgId { get; set; }
        public string AcGroup { get; set; }
        public string AcManager { get; set; }
        public string AcManagerEmail { get; set; }
        public string AcPhone1 { get; set; }
        public string AcTown { get; set; }
        public string AcCounty { get; set; }
        public string AcPostcode { get; set; }
        public string AcBillingTown { get; set; }
        public string AcBillingCounty { get; set; }
        public string AcBillingPostcode { get; set; }
        public string AcReference { get; set; }
        public string AcManagerSupport { get; set; }
        public string AcManagerSupportEmail { get; set; }
        public string AcIndustry { get; set; }
        public string AcIndustryHlight { get; set; }
        public string AcSource { get; set; }
        public string AcSourceHlight { get; set; }
        public string AcLabel { get; set; }
        public string AcLabelHlight { get; set; }
        public string AcLevel { get; set; }
        public string AcLevelHlight { get; set; }
        public string AcFlag { get; set; }
        public string AcFlagHlight { get; set; }
        public string Ud1 { get; set; }
        public string Ud2 { get; set; }
        public string Ud3 { get; set; }
        public string Ud4 { get; set; }
        public string Ud5 { get; set; }
        public string Ud6 { get; set; }
        public string Ud7 { get; set; }
        public string Ud8 { get; set; }
        public string Ud9 { get; set; }
        public string Ud10 { get; set; }
        public string Ud11 { get; set; }
        public string Ud12 { get; set; }
        public string Ud13 { get; set; }
        public string Ud14 { get; set; }
        public string Ud15 { get; set; }
        public decimal? UsaUd1Numeric { get; set; }
        public decimal? UsaUd2Numeric { get; set; }
        public decimal? UsaUd3Numeric { get; set; }
        public decimal? UsaUd4Numeric { get; set; }
        public decimal? UsaUd5Numeric { get; set; }
        public decimal? UsaUd6Numeric { get; set; }
        public decimal? UsaUd7Numeric { get; set; }
        public decimal? UsaUd8Numeric { get; set; }
        public decimal? UsaUd9Numeric { get; set; }
        public decimal? UsaUd10Numeric { get; set; }
        public DateTime? UsaUd1Date { get; set; }
        public DateTime? UsaUd2Date { get; set; }
        public DateTime? UsaUd3Date { get; set; }
        public DateTime? UsaUd4Date { get; set; }
        public DateTime? UsaUd5Date { get; set; }
        public DateTime? UsaUd6Date { get; set; }
        public DateTime? UsaUd7Date { get; set; }
        public DateTime? UsaUd8Date { get; set; }
        public DateTime? UsaUd9Date { get; set; }
        public DateTime? UsaUd10Date { get; set; }
        public string UsaUd1Id { get; set; }
        public string UsaUd1IdHlight { get; set; }
        public string UsaUd2Id { get; set; }
        public string UsaUd2IdHlight { get; set; }
        public string UsaUd3Id { get; set; }
        public string UsaUd3IdHlight { get; set; }
        public string UsaUd4Id { get; set; }
        public string UsaUd4IdHlight { get; set; }
        public string UsaUd5Id { get; set; }
        public string UsaUd5IdHlight { get; set; }
        public string UsaUd6Id { get; set; }
        public string UsaUd6IdHlight { get; set; }
        public string UsaUd7Id { get; set; }
        public string UsaUd7IdHlight { get; set; }
        public string UsaUd8Id { get; set; }
        public string UsaUd8IdHlight { get; set; }
        public string UsaUd9Id { get; set; }
        public string UsaUd9IdHlight { get; set; }
        public string UsaUd10Id { get; set; }
        public string UsaUd10IdHlight { get; set; }
        public string UsaType { get; set; }
        public string UsaTypeHlight { get; set; }
        public bool? UsaUd1Bit { get; set; }
        public bool? UsaUd2Bit { get; set; }
        public bool? UsaUd3Bit { get; set; }
        public bool? UsaUd4Bit { get; set; }
        public bool? UsaUd5Bit { get; set; }
        public bool? UsaUd6Bit { get; set; }
        public bool? UsaUd7Bit { get; set; }
        public bool? UsaUd8Bit { get; set; }
        public bool? UsaUd9Bit { get; set; }
        public bool? UsaUd10Bit { get; set; }
        public bool? UsaUd11Bit { get; set; }
        public bool? UsaUd12Bit { get; set; }
        public bool? UsaUd13Bit { get; set; }
        public bool? UsaUd14Bit { get; set; }
        public bool? UsaUd15Bit { get; set; }
        public bool? UsaUd16Bit { get; set; }
        public bool? UsaUd17Bit { get; set; }
        public bool? UsaUd18Bit { get; set; }
        public bool? UsaUd19Bit { get; set; }
        public bool? UsaUd20Bit { get; set; }
        public bool? UsaUd21Bit { get; set; }
        public bool? UsaUd22Bit { get; set; }
        public bool? UsaUd23Bit { get; set; }
        public bool? UsaUd24Bit { get; set; }
        public string AcUd1Id { get; set; }
        public string AcUd1IdHlight { get; set; }
        public string AcUd2Id { get; set; }
        public string AcUd2IdHlight { get; set; }
        public string AcUd3Id { get; set; }
        public string AcUd3IdHlight { get; set; }
        public string AcUd4Id { get; set; }
        public string AcUd4IdHlight { get; set; }
        public string AcUd5Id { get; set; }
        public string AcUd5IdHlight { get; set; }
        public string AcUd6Id { get; set; }
        public string AcUd6IdHlight { get; set; }
        public string AcUd7Id { get; set; }
        public string AcUd7IdHlight { get; set; }
        public string AcUd8Id { get; set; }
        public string AcUd8IdHlight { get; set; }
        public string AcUd9Id { get; set; }
        public string AcUd9IdHlight { get; set; }
        public string AcUd10Id { get; set; }
        public string AcUd10IdHlight { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public decimal? AcUd1Numeric { get; set; }
        public decimal? AcUd2Numeric { get; set; }
        public decimal? AcUd3Numeric { get; set; }
        public decimal? AcUd4Numeric { get; set; }
        public decimal? AcUd5Numeric { get; set; }
        public decimal? AcUd6Numeric { get; set; }
        public decimal? AcUd7Numeric { get; set; }
        public decimal? AcUd8Numeric { get; set; }
        public decimal? AcUd9Numeric { get; set; }
        public decimal? AcUd10Numeric { get; set; }
        public DateTime? AcUd1Date { get; set; }
        public DateTime? AcUd2Date { get; set; }
        public DateTime? AcUd3Date { get; set; }
        public DateTime? AcUd4Date { get; set; }
        public DateTime? AcUd5Date { get; set; }
        public DateTime? AcUd6Date { get; set; }
        public DateTime? AcUd7Date { get; set; }
        public DateTime? AcUd8Date { get; set; }
        public DateTime? AcUd9Date { get; set; }
        public DateTime? AcUd10Date { get; set; }
        public bool? AcUd1Bit { get; set; }
        public bool? AcUd2Bit { get; set; }
        public bool? AcUd3Bit { get; set; }
        public bool? AcUd4Bit { get; set; }
        public bool? AcUd5Bit { get; set; }
        public bool? AcUd6Bit { get; set; }
        public bool? AcUd7Bit { get; set; }
        public bool? AcUd8Bit { get; set; }
        public bool? AcUd9Bit { get; set; }
        public bool? AcUd10Bit { get; set; }
        public string AcUd1Text { get; set; }
        public string AcUd2Text { get; set; }
        public string AcUd3Text { get; set; }
        public string AcUd4Text { get; set; }
        public string AcUd5Text { get; set; }
        public string AcUd6Text { get; set; }
        public string AcUd7Text { get; set; }
        public string AcUd8Text { get; set; }
        public string AcUd9Text { get; set; }
        public string AcUd10Text { get; set; }
        public string AcUd11Text { get; set; }
        public string AcUd12Text { get; set; }
        public string AcUd13Text { get; set; }
        public string AcUd14Text { get; set; }
        public string AcUd15Text { get; set; }
        public short? UsaAccessLevel { get; set; }
        public Guid? NtIdOutlook { get; set; }
        public Guid? ParentId { get; set; }
        public string ParentSummary { get; set; }
        public Guid? StgId { get; set; }
        public Guid? SecurityId { get; set; }
        public string SecurityGroup { get; set; }
        public string SecurityObject { get; set; }
        public Guid? SecurityOwner { get; set; }
        public string PjName { get; set; }
        public string StgName { get; set; }
        public string ActName { get; set; }
        public string OpName { get; set; }
        public Guid? OwnerId { get; set; }
        public string AppointmentOwnerName { get; set; }
        public string AppointmentOwnerDept { get; set; }
        public string AppointmentOwnerGroup { get; set; }
        public string ShortCode { get; set; }
        public Guid? SitId { get; set; }
        public string SiteName { get; set; }
    }
}
